// This file is auto-generated by @hey-api/openapi-ts

export const BatchTestCaseFileValidateErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/TestCaseFileValidateError',
      },
      type: 'array',
      title: 'Detail',
    },
  },
  type: 'object',
  required: ['detail'],
  title: 'BatchTestCaseFileValidateError',
} as const;

export const BearerResponseSchema = {
  properties: {
    access_token: {
      type: 'string',
      title: 'Access Token',
    },
    token_type: {
      type: 'string',
      title: 'Token Type',
    },
  },
  type: 'object',
  required: ['access_token', 'token_type'],
  title: 'BearerResponse',
} as const;

export const Body_auth_jwt_login_api_auth_jwt_login_postSchema = {
  properties: {
    grant_type: {
      anyOf: [
        {
          type: 'string',
          pattern: '^password$',
        },
        {
          type: 'null',
        },
      ],
      title: 'Grant Type',
    },
    username: {
      type: 'string',
      title: 'Username',
    },
    password: {
      type: 'string',
      format: 'password',
      title: 'Password',
    },
    scope: {
      type: 'string',
      title: 'Scope',
      default: '',
    },
    client_id: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Client Id',
    },
    client_secret: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      format: 'password',
      title: 'Client Secret',
    },
  },
  type: 'object',
  required: ['username', 'password'],
  title: 'Body_auth_jwt_login_api_auth_jwt_login_post',
} as const;

export const Body_importTestCaseFileSchema = {
  properties: {
    file: {
      type: 'string',
      format: 'binary',
      title: 'File',
    },
  },
  type: 'object',
  required: ['file'],
  title: 'Body_importTestCaseFile',
} as const;

export const Body_uploadAvatarSchema = {
  properties: {
    file: {
      type: 'string',
      format: 'binary',
      title: 'File',
    },
  },
  type: 'object',
  required: ['file'],
  title: 'Body_uploadAvatar',
} as const;

export const Body_validateTestCaseFileSchema = {
  properties: {
    file: {
      type: 'string',
      format: 'binary',
      title: 'File',
    },
  },
  type: 'object',
  required: ['file'],
  title: 'Body_validateTestCaseFile',
} as const;

export const CaseRecordSchema = {
  properties: {
    task_record_id: {
      type: 'integer',
      title: 'Task Record Id',
    },
    case_index: {
      type: 'string',
      title: 'Case Index',
    },
    start_time: {
      anyOf: [
        {
          type: 'string',
          format: 'date-time',
        },
        {
          type: 'null',
        },
      ],
      title: 'Start Time',
    },
    end_time: {
      anyOf: [
        {
          type: 'string',
          format: 'date-time',
        },
        {
          type: 'null',
        },
      ],
      title: 'End Time',
    },
    duration: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Duration',
    },
    result: {
      anyOf: [
        {
          $ref: '#/components/schemas/CaseRecordStatus',
        },
        {
          type: 'null',
        },
      ],
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['task_record_id', 'case_index', 'id'],
  title: 'CaseRecord',
} as const;

export const CaseRecordCreateItemSchema = {
  properties: {
    case_node: {
      type: 'string',
      title: 'Case Node',
    },
    result: {
      type: 'string',
      title: 'Result',
    },
    case_index: {
      type: 'string',
      title: 'Case Index',
    },
    start_time: {
      type: 'string',
      format: 'date-time',
      title: 'Start Time',
    },
    end_time: {
      type: 'string',
      format: 'date-time',
      title: 'End Time',
    },
    duration: {
      type: 'integer',
      title: 'Duration',
    },
  },
  type: 'object',
  required: [
    'case_node',
    'result',
    'case_index',
    'start_time',
    'end_time',
    'duration',
  ],
  title: 'CaseRecordCreateItem',
} as const;

export const CaseRecordStatusSchema = {
  type: 'string',
  enum: ['passed', 'failed', 'skipped', 'xfailed', 'xpassed', 'error'],
  title: 'CaseRecordStatus',
} as const;

export const CaseResultCreateSchema = {
  properties: {
    record_id: {
      type: 'string',
      title: 'Record Id',
    },
    result: {
      $ref: '#/components/schemas/CaseRecordCreateItem',
    },
  },
  type: 'object',
  required: ['record_id', 'result'],
  title: 'CaseResultCreate',
} as const;

export const ContainerStatusSchema = {
  type: 'string',
  enum: ['Running', 'Stopped', 'Failed', 'Succeeded', 'Unknown'],
  title: 'ContainerStatus',
} as const;

export const ContainerStopDataSchema = {
  properties: {
    status: {
      anyOf: [
        {
          $ref: '#/components/schemas/ContainerStatus',
        },
        {
          type: 'null',
        },
      ],
    },
    container_id: {
      type: 'string',
      title: 'Container Id',
    },
    timestamp: {
      type: 'string',
      title: 'Timestamp',
    },
  },
  type: 'object',
  required: ['container_id', 'timestamp'],
  title: 'ContainerStopData',
} as const;

export const EnvVarSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    value: {
      type: 'string',
      title: 'Value',
    },
  },
  type: 'object',
  required: ['name', 'value'],
  title: 'EnvVar',
} as const;

export const ErrorModelSchema = {
  properties: {
    detail: {
      anyOf: [
        {
          type: 'string',
        },
        {
          additionalProperties: {
            type: 'string',
          },
          type: 'object',
        },
      ],
      title: 'Detail',
    },
  },
  type: 'object',
  required: ['detail'],
  title: 'ErrorModel',
} as const;

export const GenericErrorResponseSchema = {
  properties: {
    detail: {
      type: 'string',
      title: 'Detail',
    },
  },
  type: 'object',
  required: ['detail'],
  title: 'GenericErrorResponse',
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError',
      },
      type: 'array',
      title: 'Detail',
    },
  },
  type: 'object',
  title: 'HTTPValidationError',
} as const;

export const ListResponse_Server_Schema = {
  properties: {
    list: {
      items: {
        $ref: '#/components/schemas/Server',
      },
      type: 'array',
      title: 'List',
      default: [],
    },
    total: {
      type: 'integer',
      title: 'Total',
      default: 0,
    },
  },
  type: 'object',
  title: 'ListResponse[Server]',
} as const;

export const ProjectSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    git_repo: {
      type: 'string',
      title: 'Git Repo',
    },
    branch: {
      type: 'string',
      title: 'Branch',
    },
    owners: {
      items: {
        $ref: '#/components/schemas/UserSearch',
      },
      type: 'array',
      title: 'Owners',
    },
    qas: {
      items: {
        $ref: '#/components/schemas/UserSearch',
      },
      type: 'array',
      title: 'Qas',
    },
    devs: {
      items: {
        $ref: '#/components/schemas/UserSearch',
      },
      type: 'array',
      title: 'Devs',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
    },
    updated_at: {
      type: 'string',
      format: 'date-time',
      title: 'Updated At',
    },
  },
  type: 'object',
  required: [
    'name',
    'git_repo',
    'branch',
    'owners',
    'qas',
    'devs',
    'id',
    'created_at',
    'updated_at',
  ],
  title: 'Project',
} as const;

export const ProjectCreateSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    git_repo: {
      type: 'string',
      title: 'Git Repo',
    },
    branch: {
      type: 'string',
      title: 'Branch',
    },
    owners: {
      items: {
        $ref: '#/components/schemas/UserSearch',
      },
      type: 'array',
      title: 'Owners',
    },
    qas: {
      items: {
        $ref: '#/components/schemas/UserSearch',
      },
      type: 'array',
      title: 'Qas',
    },
    devs: {
      items: {
        $ref: '#/components/schemas/UserSearch',
      },
      type: 'array',
      title: 'Devs',
    },
  },
  type: 'object',
  required: ['name', 'git_repo', 'branch', 'owners', 'qas', 'devs'],
  title: 'ProjectCreate',
} as const;

export const ProjectListSchema = {
  properties: {
    list: {
      items: {
        $ref: '#/components/schemas/Project',
      },
      type: 'array',
      title: 'List',
    },
    total: {
      type: 'integer',
      title: 'Total',
    },
  },
  type: 'object',
  required: ['list', 'total'],
  title: 'ProjectList',
} as const;

export const ProjectOptionsSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['name', 'id'],
  title: 'ProjectOptions',
} as const;

export const ProjectUpdateSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    git_repo: {
      type: 'string',
      title: 'Git Repo',
    },
    branch: {
      type: 'string',
      title: 'Branch',
    },
    owners: {
      items: {
        $ref: '#/components/schemas/UserSearch',
      },
      type: 'array',
      title: 'Owners',
    },
    qas: {
      items: {
        $ref: '#/components/schemas/UserSearch',
      },
      type: 'array',
      title: 'Qas',
    },
    devs: {
      items: {
        $ref: '#/components/schemas/UserSearch',
      },
      type: 'array',
      title: 'Devs',
    },
  },
  type: 'object',
  required: ['name', 'git_repo', 'branch', 'owners', 'qas', 'devs'],
  title: 'ProjectUpdate',
} as const;

export const ReadMessageRequestSchema = {
  properties: {
    ids: {
      items: {
        type: 'integer',
      },
      type: 'array',
      title: 'Ids',
      default: [],
    },
  },
  type: 'object',
  title: 'ReadMessageRequest',
} as const;

export const ServerSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
      description: '服务器名称',
    },
    project_id: {
      type: 'integer',
      title: 'Project Id',
      description: '所属项目ID',
    },
    status: {
      anyOf: [
        {
          $ref: '#/components/schemas/ServerStatus',
        },
        {
          type: 'null',
        },
      ],
      description: '环境状态',
      default: 'IDLE',
    },
    ip: {
      type: 'string',
      title: 'Ip',
      description: 'IP地址',
    },
    sn: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Sn',
      description: '序列号',
    },
    id: {
      type: 'integer',
      title: 'Id',
      description: '资源ID',
    },
    owner_id: {
      type: 'integer',
      title: 'Owner Id',
      description: '创建人ID',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
      description: '创建时间',
    },
    updated_at: {
      type: 'string',
      format: 'date-time',
      title: 'Updated At',
      description: '更新时间',
    },
    owner: {
      anyOf: [
        {
          $ref: '#/components/schemas/UserSearch',
        },
        {
          type: 'null',
        },
      ],
      description: '责任人',
    },
    bmc_ip: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Bmc Ip',
      description: 'BMC IP地址',
    },
    bmc_username: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Bmc Username',
      description: 'BMC 用户名',
    },
    bmc_password: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Bmc Password',
      description: 'BMC 密码',
    },
    port: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Port',
      description: '服务端口',
    },
    username: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Username',
      description: '用户名',
    },
    password: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Password',
      description: '密码',
    },
  },
  type: 'object',
  required: [
    'name',
    'project_id',
    'ip',
    'id',
    'owner_id',
    'created_at',
    'updated_at',
    'bmc_ip',
    'bmc_username',
    'bmc_password',
    'port',
    'username',
    'password',
  ],
  title: 'Server',
  description: 'Schema for retrieving a test server',
} as const;

export const ServerCreateSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
      description: '服务器名称',
    },
    ip: {
      type: 'string',
      title: 'Ip',
      description: 'IP地址',
    },
    sn: {
      type: 'string',
      title: 'Sn',
      description: '序列号',
    },
    bmc_ip: {
      type: 'string',
      title: 'Bmc Ip',
      description: 'BMC IP地址',
    },
    bmc_username: {
      type: 'string',
      title: 'Bmc Username',
      description: 'BMC 用户名',
    },
    bmc_password: {
      type: 'string',
      title: 'Bmc Password',
      description: 'BMC 密码',
    },
    port: {
      type: 'integer',
      title: 'Port',
      description: '服务端口',
    },
    username: {
      type: 'string',
      title: 'Username',
      description: '用户名',
    },
    password: {
      type: 'string',
      title: 'Password',
      description: '密码',
    },
    status: {
      anyOf: [
        {
          $ref: '#/components/schemas/ServerStatus',
        },
        {
          type: 'null',
        },
      ],
      description: '环境状态',
      default: 'IDLE',
    },
  },
  type: 'object',
  required: [
    'name',
    'ip',
    'sn',
    'bmc_ip',
    'bmc_username',
    'bmc_password',
    'port',
    'username',
    'password',
  ],
  title: 'ServerCreate',
  description: 'Schema for creating a new server',
} as const;

export const ServerInTaskSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
      description: '服务器名称',
    },
    ip: {
      type: 'string',
      title: 'Ip',
      description: 'IP地址',
    },
    sn: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Sn',
      description: '序列号',
    },
    id: {
      type: 'integer',
      title: 'Id',
      description: '资源ID',
    },
    bmc_ip: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Bmc Ip',
      description: 'BMC IP地址',
    },
    bmc_username: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Bmc Username',
      description: 'BMC 用户名',
    },
    port: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Port',
      description: '服务端口',
    },
    username: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Username',
      description: '用户名',
    },
  },
  type: 'object',
  required: ['name', 'ip', 'id', 'bmc_ip', 'bmc_username', 'port', 'username'],
  title: 'ServerInTask',
} as const;

export const ServerOptionsSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
      description: '资源ID',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: '环境名称',
    },
  },
  type: 'object',
  required: ['id', 'name'],
  title: 'ServerOptions',
  description: 'Schema for retrieving a test server options',
} as const;

export const ServerStatusSchema = {
  type: 'string',
  enum: ['IDLE', 'IN_USE', 'MAINTENANCE', 'ERROR', 'UNKNOWN'],
  title: 'ServerStatus',
} as const;

export const ServerUpdateSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
      description: '服务器名称',
    },
    ip: {
      type: 'string',
      title: 'Ip',
      description: 'IP地址',
    },
    sn: {
      type: 'string',
      title: 'Sn',
      description: '序列号',
    },
    bmc_ip: {
      type: 'string',
      title: 'Bmc Ip',
      description: 'BMC IP地址',
    },
    bmc_username: {
      type: 'string',
      title: 'Bmc Username',
      description: 'BMC 用户名',
    },
    bmc_password: {
      type: 'string',
      title: 'Bmc Password',
      description: 'BMC 密码',
    },
    port: {
      type: 'integer',
      title: 'Port',
      description: '服务端口',
    },
    username: {
      type: 'string',
      title: 'Username',
      description: '用户名',
    },
    password: {
      type: 'string',
      title: 'Password',
      description: '密码',
    },
    status: {
      anyOf: [
        {
          $ref: '#/components/schemas/ServerStatus',
        },
        {
          type: 'null',
        },
      ],
      description: '环境状态',
      default: 'IDLE',
    },
  },
  type: 'object',
  required: [
    'name',
    'ip',
    'sn',
    'bmc_ip',
    'bmc_username',
    'bmc_password',
    'port',
    'username',
    'password',
  ],
  title: 'ServerUpdate',
  description: 'Schema for updating a test server',
} as const;

export const TaskConfigSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
    env_vars: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/EnvVar',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Env Vars',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
    project_id: {
      type: 'integer',
      title: 'Project Id',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
    },
    updated_at: {
      type: 'string',
      format: 'date-time',
      title: 'Updated At',
    },
  },
  type: 'object',
  required: ['name', 'id', 'project_id', 'created_at', 'updated_at'],
  title: 'TaskConfig',
} as const;

export const TaskConfigCreateSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
    env_vars: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/EnvVar',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Env Vars',
    },
  },
  type: 'object',
  required: ['name'],
  title: 'TaskConfigCreate',
} as const;

export const TaskConfigListSchema = {
  properties: {
    list: {
      items: {
        $ref: '#/components/schemas/TaskConfigListItem',
      },
      type: 'array',
      title: 'List',
    },
    total: {
      type: 'integer',
      title: 'Total',
    },
  },
  type: 'object',
  required: ['list', 'total'],
  title: 'TaskConfigList',
} as const;

export const TaskConfigListItemSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
    env_vars: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/EnvVar',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Env Vars',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
    project_id: {
      type: 'integer',
      title: 'Project Id',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
    },
    updated_at: {
      type: 'string',
      format: 'date-time',
      title: 'Updated At',
    },
    owner: {
      $ref: '#/components/schemas/UserSearch',
    },
  },
  type: 'object',
  required: ['name', 'id', 'project_id', 'created_at', 'updated_at', 'owner'],
  title: 'TaskConfigListItem',
} as const;

export const TaskConfigOptionsSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['name', 'id'],
  title: 'TaskConfigOptions',
} as const;

export const TaskConfigUpdateSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
    env_vars: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/EnvVar',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Env Vars',
    },
  },
  type: 'object',
  required: ['name'],
  title: 'TaskConfigUpdate',
} as const;

export const TaskRecordSchema = {
  properties: {
    project_id: {
      type: 'integer',
      title: 'Project Id',
    },
    testplan_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Testplan Id',
    },
    failed_continue: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Failed Continue',
    },
    status: {
      anyOf: [
        {
          $ref: '#/components/schemas/TaskRecordStatus',
        },
        {
          type: 'null',
        },
      ],
    },
    branch: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Branch',
    },
    image: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Image',
    },
    repo: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Repo',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
    task_id: {
      type: 'integer',
      title: 'Task Id',
    },
    passed: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Passed',
    },
    failed: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Failed',
    },
    total: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Total',
    },
    created_at: {
      anyOf: [
        {
          type: 'string',
          format: 'date-time',
        },
        {
          type: 'null',
        },
      ],
      title: 'Created At',
    },
    case_records: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/CaseRecord',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Case Records',
    },
  },
  type: 'object',
  required: ['project_id', 'id', 'task_id'],
  title: 'TaskRecord',
} as const;

export const TaskRecordListSchema = {
  properties: {
    list: {
      items: {
        $ref: '#/components/schemas/TaskRecord',
      },
      type: 'array',
      title: 'List',
    },
    total: {
      type: 'integer',
      title: 'Total',
    },
  },
  type: 'object',
  required: ['list', 'total'],
  title: 'TaskRecordList',
} as const;

export const TaskRecordStatusSchema = {
  type: 'string',
  enum: ['Created', 'Running', 'Passed', 'Failed', 'Canceled', 'Error', ''],
  title: 'TaskRecordStatus',
} as const;

export const TaskRunOutSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    creater: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Creater',
      default: 'System',
    },
    task_id: {
      type: 'integer',
      title: 'Task Id',
    },
    container_id: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Container Id',
    },
    agent_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Agent Id',
    },
  },
  type: 'object',
  required: ['id', 'task_id'],
  title: 'TaskRunOut',
} as const;

export const TaskStatusSchema = {
  type: 'string',
  enum: ['Created', 'Running', 'Passed', 'Failed', 'Canceled', 'Error'],
  title: 'TaskStatus',
} as const;

export const TestCaseSchema = {
  properties: {
    index: {
      type: 'string',
      title: 'Index',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    objective: {
      type: 'string',
      title: 'Objective',
    },
    priority: {
      type: 'string',
      title: 'Priority',
    },
    automated: {
      type: 'integer',
      title: 'Automated',
      default: 0,
    },
    automation: {
      type: 'integer',
      title: 'Automation',
      default: 0,
    },
    comment: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Comment',
    },
    depends: {
      anyOf: [
        {
          items: {},
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Depends',
    },
    node_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Node Id',
      default: 0,
    },
    module: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Module',
      default: '',
    },
    test_type: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Test Type',
      default: '',
    },
    expected: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Expected',
      default: '',
    },
    setup: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Setup',
      default: '',
    },
    step: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Step',
      default: '',
    },
    topo: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Topo',
      default: '',
    },
    project_id: {
      type: 'integer',
      title: 'Project Id',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
    },
    updated_at: {
      type: 'string',
      format: 'date-time',
      title: 'Updated At',
    },
  },
  type: 'object',
  required: [
    'index',
    'name',
    'objective',
    'priority',
    'project_id',
    'id',
    'created_at',
    'updated_at',
  ],
  title: 'TestCase',
} as const;

export const TestCaseCreateSchema = {
  properties: {
    index: {
      type: 'string',
      title: 'Index',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    objective: {
      type: 'string',
      title: 'Objective',
    },
    priority: {
      type: 'string',
      title: 'Priority',
    },
    automated: {
      type: 'integer',
      title: 'Automated',
      default: 0,
    },
    automation: {
      type: 'integer',
      title: 'Automation',
      default: 0,
    },
    comment: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Comment',
    },
    depends: {
      anyOf: [
        {
          items: {},
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Depends',
    },
    node_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Node Id',
      default: 0,
    },
    module: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Module',
      default: '',
    },
    test_type: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Test Type',
      default: '',
    },
    expected: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Expected',
      default: '',
    },
    setup: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Setup',
      default: '',
    },
    step: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Step',
      default: '',
    },
    topo: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Topo',
      default: '',
    },
  },
  type: 'object',
  required: ['index', 'name', 'objective', 'priority'],
  title: 'TestCaseCreate',
} as const;

export const TestCaseFileValidateErrorSchema = {
  properties: {
    sheet: {
      type: 'string',
      title: 'Sheet',
    },
    type: {
      type: 'string',
      title: 'Type',
    },
    errors: {
      items: {
        type: 'string',
      },
      type: 'array',
      title: 'Errors',
    },
  },
  type: 'object',
  required: ['sheet', 'type', 'errors'],
  title: 'TestCaseFileValidateError',
} as const;

export const TestCaseListSchema = {
  properties: {
    list: {
      items: {
        $ref: '#/components/schemas/TestCase',
      },
      type: 'array',
      title: 'List',
    },
    total: {
      type: 'integer',
      title: 'Total',
    },
  },
  type: 'object',
  required: ['list', 'total'],
  title: 'TestCaseList',
} as const;

export const TestCaseNodeSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    comment: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Comment',
    },
    parent_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Parent Id',
    },
    creater: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Creater',
      default: 'Linlin',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
    project_id: {
      type: 'integer',
      title: 'Project Id',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
    },
    updated_at: {
      type: 'string',
      format: 'date-time',
      title: 'Updated At',
    },
  },
  type: 'object',
  required: ['name', 'id', 'project_id', 'created_at', 'updated_at'],
  title: 'TestCaseNode',
} as const;

export const TestCaseNodeCreateSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    comment: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Comment',
    },
    parent_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Parent Id',
    },
    creater: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Creater',
      default: 'Linlin',
    },
  },
  type: 'object',
  required: ['name'],
  title: 'TestCaseNodeCreate',
} as const;

export const TestCaseNodeListSchema = {
  properties: {
    list: {
      items: {
        $ref: '#/components/schemas/TestCaseNode',
      },
      type: 'array',
      title: 'List',
    },
    total: {
      type: 'integer',
      title: 'Total',
    },
  },
  type: 'object',
  required: ['list', 'total'],
  title: 'TestCaseNodeList',
} as const;

export const TestCaseNodeTreeItemOfTaskSchema = {
  properties: {
    key: {
      type: 'string',
      title: 'Key',
    },
    title: {
      type: 'string',
      title: 'Title',
    },
    children: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/TestCaseNodeTreeItemOfTask',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Children',
      default: [],
    },
    case_count: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Case Count',
      default: 0,
    },
    selected_case_count: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Selected Case Count',
      default: 0,
    },
  },
  type: 'object',
  required: ['key', 'title'],
  title: 'TestCaseNodeTreeItemOfTask',
} as const;

export const TestCaseNodeUpdateSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Name',
    },
    comment: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Comment',
    },
    parent_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Parent Id',
    },
  },
  type: 'object',
  title: 'TestCaseNodeUpdate',
} as const;

export const TestCaseUpdateSchema = {
  properties: {
    index: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Index',
    },
    name: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Name',
    },
    objective: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Objective',
    },
    priority: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Priority',
    },
    automated: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Automated',
    },
    automation: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Automation',
    },
    comment: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Comment',
    },
    depends: {
      anyOf: [
        {
          items: {},
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Depends',
    },
    node_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Node Id',
      default: 0,
    },
    module: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Module',
      default: '',
    },
    test_type: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Test Type',
      default: '',
    },
    expected: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Expected',
      default: '',
    },
    setup: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Setup',
      default: '',
    },
    step: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Step',
      default: '',
    },
    topo: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Topo',
      default: '',
    },
  },
  type: 'object',
  title: 'TestCaseUpdate',
} as const;

export const TestPlanSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    project_id: {
      type: 'integer',
      title: 'Project Id',
    },
    stage: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Stage',
    },
    owner_id: {
      type: 'string',
      title: 'Owner Id',
    },
    status: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Status',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
    },
    updated_at: {
      type: 'string',
      format: 'date-time',
      title: 'Updated At',
    },
  },
  type: 'object',
  required: [
    'name',
    'project_id',
    'owner_id',
    'id',
    'created_at',
    'updated_at',
  ],
  title: 'TestPlan',
} as const;

export const TestPlanCreateSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    project_id: {
      type: 'integer',
      title: 'Project Id',
    },
    stage: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Stage',
    },
    owner_id: {
      type: 'string',
      title: 'Owner Id',
    },
    status: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Status',
    },
    case_indexs: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Case Indexs',
    },
  },
  type: 'object',
  required: ['name', 'project_id', 'owner_id'],
  title: 'TestPlanCreate',
} as const;

export const TestPlanListSchema = {
  properties: {
    list: {
      items: {
        $ref: '#/components/schemas/TestPlan',
      },
      type: 'array',
      title: 'List',
    },
    total: {
      type: 'integer',
      title: 'Total',
    },
  },
  type: 'object',
  required: ['list', 'total'],
  title: 'TestPlanList',
} as const;

export const TestPlanUpdateSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Name',
    },
    project_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Project Id',
    },
    stage: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Stage',
    },
    owner_id: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Owner Id',
    },
    status: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Status',
    },
    case_indexs: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Case Indexs',
    },
  },
  type: 'object',
  title: 'TestPlanUpdate',
} as const;

export const TestPlanWithRelationsSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    project_id: {
      type: 'integer',
      title: 'Project Id',
    },
    stage: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Stage',
    },
    owner_id: {
      type: 'string',
      title: 'Owner Id',
    },
    status: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Status',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
    },
    updated_at: {
      type: 'string',
      format: 'date-time',
      title: 'Updated At',
    },
    owner: {
      anyOf: [
        {
          $ref: '#/components/schemas/UserRead',
        },
        {
          type: 'null',
        },
      ],
    },
    cases: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/TestCase',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Cases',
    },
  },
  type: 'object',
  required: [
    'name',
    'project_id',
    'owner_id',
    'id',
    'created_at',
    'updated_at',
  ],
  title: 'TestPlanWithRelations',
} as const;

export const TestTaskSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    failed_continue: {
      type: 'integer',
      title: 'Failed Continue',
      default: 0,
    },
    lark_notice: {
      type: 'integer',
      title: 'Lark Notice',
      default: 0,
    },
    config_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Config Id',
    },
    server_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Server Id',
    },
    lark_subscribe: {
      anyOf: [
        {
          items: {},
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Lark Subscribe',
      default: [],
    },
    cases_index: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Cases Index',
      default: [],
    },
    desc: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Desc',
      default: '',
    },
    comment: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Comment',
      default: '',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
    owner: {
      $ref: '#/components/schemas/UserSearch',
    },
    status: {
      anyOf: [
        {
          $ref: '#/components/schemas/TaskStatus',
        },
        {
          type: 'null',
        },
      ],
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
    },
    updated_at: {
      type: 'string',
      format: 'date-time',
      title: 'Updated At',
    },
  },
  type: 'object',
  required: ['name', 'id', 'owner', 'created_at', 'updated_at'],
  title: 'TestTask',
} as const;

export const TestTaskCreateSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    failed_continue: {
      type: 'integer',
      title: 'Failed Continue',
      default: 0,
    },
    lark_notice: {
      type: 'integer',
      title: 'Lark Notice',
      default: 0,
    },
    config_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Config Id',
    },
    server_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Server Id',
    },
    lark_subscribe: {
      anyOf: [
        {
          items: {},
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Lark Subscribe',
      default: [],
    },
    cases: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Cases',
      default: [],
    },
    desc: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Desc',
      default: '',
    },
    comment: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Comment',
      default: '',
    },
  },
  type: 'object',
  required: ['name'],
  title: 'TestTaskCreate',
} as const;

export const TestTaskListSchema = {
  properties: {
    list: {
      items: {
        $ref: '#/components/schemas/TestTaskListItem',
      },
      type: 'array',
      title: 'List',
    },
    total: {
      type: 'integer',
      title: 'Total',
    },
  },
  type: 'object',
  required: ['list', 'total'],
  title: 'TestTaskList',
} as const;

export const TestTaskListItemSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    owner: {
      $ref: '#/components/schemas/UserSearch',
    },
    config: {
      anyOf: [
        {
          $ref: '#/components/schemas/TaskConfig',
        },
        {
          type: 'null',
        },
      ],
    },
    status: {
      anyOf: [
        {
          $ref: '#/components/schemas/TaskStatus',
        },
        {
          type: 'null',
        },
      ],
    },
    server: {
      anyOf: [
        {
          $ref: '#/components/schemas/ServerInTask',
        },
        {
          type: 'null',
        },
      ],
    },
    failed_continue: {
      type: 'integer',
      title: 'Failed Continue',
      default: 0,
    },
    lark_notice: {
      type: 'integer',
      title: 'Lark Notice',
      default: 0,
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
    },
    updated_at: {
      type: 'string',
      format: 'date-time',
      title: 'Updated At',
    },
  },
  type: 'object',
  required: ['id', 'name', 'owner', 'created_at', 'updated_at'],
  title: 'TestTaskListItem',
} as const;

export const TestTaskUpdateSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    failed_continue: {
      type: 'integer',
      title: 'Failed Continue',
      default: 0,
    },
    lark_notice: {
      type: 'integer',
      title: 'Lark Notice',
      default: 0,
    },
    config_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Config Id',
    },
    server_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Server Id',
    },
    lark_subscribe: {
      anyOf: [
        {
          items: {},
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Lark Subscribe',
      default: [],
    },
    cases: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Cases',
      default: [],
    },
    desc: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Desc',
      default: '',
    },
    comment: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Comment',
      default: '',
    },
  },
  type: 'object',
  required: ['name'],
  title: 'TestTaskUpdate',
} as const;

export const UpdateUserAvatarSchema = {
  properties: {
    avatar: {
      type: 'string',
      title: 'Avatar',
    },
  },
  type: 'object',
  required: ['avatar'],
  title: 'UpdateUserAvatar',
} as const;

export const UserCreateSchema = {
  properties: {
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
    password: {
      type: 'string',
      title: 'Password',
    },
    is_active: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Is Active',
      default: true,
    },
    is_superuser: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Is Superuser',
      default: false,
    },
    is_verified: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Is Verified',
      default: false,
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    en_name: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'En Name',
    },
    avatar: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Avatar',
    },
    union_id: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Union Id',
    },
  },
  type: 'object',
  required: ['email', 'password', 'name'],
  title: 'UserCreate',
} as const;

export const UserReadSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
    is_active: {
      type: 'boolean',
      title: 'Is Active',
      default: true,
    },
    is_superuser: {
      type: 'boolean',
      title: 'Is Superuser',
      default: false,
    },
    is_verified: {
      type: 'boolean',
      title: 'Is Verified',
      default: false,
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    en_name: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'En Name',
    },
    extra: {
      anyOf: [
        {
          additionalProperties: true,
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Extra',
      default: {},
    },
    union_id: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Union Id',
    },
    avatar: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Avatar',
    },
    permissions: {
      anyOf: [
        {
          additionalProperties: {
            items: {
              type: 'string',
            },
            type: 'array',
          },
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Permissions',
      default: {},
    },
  },
  type: 'object',
  required: ['id', 'email', 'name'],
  title: 'UserRead',
} as const;

export const UserSearchSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    email: {
      type: 'string',
      title: 'Email',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    en_name: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'En Name',
    },
    union_id: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Union Id',
    },
    avatar: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Avatar',
    },
  },
  type: 'object',
  required: ['id', 'email', 'name'],
  title: 'UserSearch',
} as const;

export const UserUpdateSchema = {
  properties: {
    password: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Password',
    },
    email: {
      anyOf: [
        {
          type: 'string',
          format: 'email',
        },
        {
          type: 'null',
        },
      ],
      title: 'Email',
    },
    is_active: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Is Active',
    },
    is_superuser: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Is Superuser',
    },
    is_verified: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Is Verified',
    },
    name: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Name',
    },
    en_name: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'En Name',
    },
  },
  type: 'object',
  title: 'UserUpdate',
} as const;

export const ValidateSuccessResponseSchema = {
  properties: {
    message: {
      type: 'string',
      title: 'Message',
    },
    valid_sheets: {
      items: {
        type: 'string',
      },
      type: 'array',
      title: 'Valid Sheets',
    },
    warnings: {
      items: {
        $ref: '#/components/schemas/TestCaseFileValidateError',
      },
      type: 'array',
      title: 'Warnings',
      default: [],
    },
  },
  type: 'object',
  required: ['message', 'valid_sheets'],
  title: 'ValidateSuccessResponse',
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string',
          },
          {
            type: 'integer',
          },
        ],
      },
      type: 'array',
      title: 'Location',
    },
    msg: {
      type: 'string',
      title: 'Message',
    },
    type: {
      type: 'string',
      title: 'Error Type',
    },
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError',
} as const;
