// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  urlSearchParamsBodySerializer,
  formDataBodySerializer,
} from './client';
import type {
  AuthJwtLoginApiAuthJwtLoginPostData,
  AuthJwtLoginApiAuthJwtLoginPostResponses,
  AuthJwtLoginApiAuthJwtLoginPostErrors,
  AuthJwtLogoutApiAuthJwtLogoutPostData,
  AuthJwtLogoutApiAuthJwtLogoutPostResponses,
  AuthJwtLogoutApiAuthJwtLogoutPostErrors,
  RegisterRegisterApiAuthRegisterPostData,
  RegisterRegisterApiAuthRegisterPostResponses,
  RegisterRegisterApiAuthRegisterPostErrors,
  UsersCurrentUserApiUsersMeGetData,
  UsersCurrentUserApiUsersMeGetResponses,
  UsersCurrentUserApiUsersMeGetErrors,
  UsersPatchCurrentUserApiUsersMePatchData,
  UsersPatchCurrentUserApiUsersMePatchResponses,
  UsersPatchCurrentUserApiUsersMePatchErrors,
  SearchUserData,
  SearchUserResponses,
  SearchUserErrors,
  UploadAvatarData,
  UploadAvatarResponses,
  UploadAvatarErrors,
  UsersDeleteUserApiUsersIdDeleteData,
  UsersDeleteUserApiUsersIdDeleteResponses,
  UsersDeleteUserApiUsersIdDeleteErrors,
  UsersUserApiUsersIdGetData,
  UsersUserApiUsersIdGetResponses,
  UsersUserApiUsersIdGetErrors,
  UsersPatchUserApiUsersIdPatchData,
  UsersPatchUserApiUsersIdPatchResponses,
  UsersPatchUserApiUsersIdPatchErrors,
  LarkCallbackData,
  LarkCallbackResponses,
  LarkCallbackErrors,
  ListProjectData,
  ListProjectResponses,
  ListProjectErrors,
  CreateProjectData,
  CreateProjectResponses,
  CreateProjectErrors,
  ListProjectOptionsData,
  ListProjectOptionsResponses,
  DeleteProjectData,
  DeleteProjectResponses,
  DeleteProjectErrors,
  GetProjectData,
  GetProjectResponses,
  GetProjectErrors,
  UpdateProjectData,
  UpdateProjectResponses,
  UpdateProjectErrors,
  ReadDatasApiTestPlansGetData,
  ReadDatasApiTestPlansGetResponses,
  ReadDatasApiTestPlansGetErrors,
  CreateDataApiTestPlansPostData,
  CreateDataApiTestPlansPostResponses,
  CreateDataApiTestPlansPostErrors,
  DeleteDataApiTestPlansIdDeleteData,
  DeleteDataApiTestPlansIdDeleteResponses,
  DeleteDataApiTestPlansIdDeleteErrors,
  ReadDataApiTestPlansIdGetData,
  ReadDataApiTestPlansIdGetResponses,
  ReadDataApiTestPlansIdGetErrors,
  UpdateDataApiTestPlansIdPutData,
  UpdateDataApiTestPlansIdPutResponses,
  UpdateDataApiTestPlansIdPutErrors,
  ListTestCaseData,
  ListTestCaseResponses,
  ListTestCaseErrors,
  CreateTestCaseData,
  CreateTestCaseResponses,
  CreateTestCaseErrors,
  DeleteTestCaseData,
  DeleteTestCaseResponses,
  DeleteTestCaseErrors,
  GetTestCaseData,
  GetTestCaseResponses,
  GetTestCaseErrors,
  UpdateTestCaseData,
  UpdateTestCaseResponses,
  UpdateTestCaseErrors,
  ValidateTestCaseFileData,
  ValidateTestCaseFileResponses,
  ValidateTestCaseFileErrors,
  ImportTestCaseFileData,
  ImportTestCaseFileResponses,
  ImportTestCaseFileErrors,
  ListTestCaseNodeData,
  ListTestCaseNodeResponses,
  ListTestCaseNodeErrors,
  CreateTestCaseNodeData,
  CreateTestCaseNodeResponses,
  CreateTestCaseNodeErrors,
  ListTestCaseNodeTreeData,
  ListTestCaseNodeTreeResponses,
  ListTestCaseNodeTreeErrors,
  ListTestCaseNodeTreeCasesData,
  ListTestCaseNodeTreeCasesResponses,
  ListTestCaseNodeTreeCasesErrors,
  DeleteTestCaseNodeData,
  DeleteTestCaseNodeResponses,
  DeleteTestCaseNodeErrors,
  GetTestCaseNodeData,
  GetTestCaseNodeResponses,
  GetTestCaseNodeErrors,
  UpdateTestCaseNodeData,
  UpdateTestCaseNodeResponses,
  UpdateTestCaseNodeErrors,
  ListTestTaskData,
  ListTestTaskResponses,
  ListTestTaskErrors,
  CreateTestTaskData,
  CreateTestTaskResponses,
  CreateTestTaskErrors,
  DeleteTestTaskData,
  DeleteTestTaskResponses,
  DeleteTestTaskErrors,
  GetTestTaskData,
  GetTestTaskResponses,
  GetTestTaskErrors,
  UpdateTestTaskData,
  UpdateTestTaskResponses,
  UpdateTestTaskErrors,
  RunTestTaskData,
  RunTestTaskResponses,
  RunTestTaskErrors,
  GetTestTaskTreeData,
  GetTestTaskTreeResponses,
  GetTestTaskTreeErrors,
  GetTestTaskLogSseData,
  GetTestTaskLogSseResponses,
  GetTestTaskLogSseErrors,
  ListTestTaskRecordData,
  ListTestTaskRecordResponses,
  ListTestTaskRecordErrors,
  ListTaskConfigsData,
  ListTaskConfigsResponses,
  ListTaskConfigsErrors,
  CreateTaskConfigData,
  CreateTaskConfigResponses,
  CreateTaskConfigErrors,
  ListTaskConfigOptionsData,
  ListTaskConfigOptionsResponses,
  ListTaskConfigOptionsErrors,
  DeleteTaskConfigData,
  DeleteTaskConfigResponses,
  DeleteTaskConfigErrors,
  GetTaskConfigData,
  GetTaskConfigResponses,
  GetTaskConfigErrors,
  UpdateTaskConfigData,
  UpdateTaskConfigResponses,
  UpdateTaskConfigErrors,
  GetTestTaskLogFileData,
  GetTestTaskLogFileResponses,
  GetTestTaskLogFileErrors,
  ContainerStopTestTaskData,
  ContainerStopTestTaskResponses,
  ContainerStopTestTaskErrors,
  CaseResultApiTestTaskCaseResultPostData,
  CaseResultApiTestTaskCaseResultPostResponses,
  CaseResultApiTestTaskCaseResultPostErrors,
  ListServerData,
  ListServerResponses,
  ListServerErrors,
  CreateServerData,
  CreateServerResponses,
  CreateServerErrors,
  ListServerOptionsData,
  ListServerOptionsResponses,
  ListServerOptionsErrors,
  DeleteServerData,
  DeleteServerResponses,
  DeleteServerErrors,
  GetServerData,
  GetServerResponses,
  GetServerErrors,
  UpdateServerData,
  UpdateServerResponses,
  UpdateServerErrors,
  ReadMessageApiMessageReadPostData,
  ReadMessageApiMessageReadPostResponses,
  ReadMessageApiMessageReadPostErrors,
  ListDataApiMessageListGetData,
  ListDataApiMessageListGetResponses,
  GetDataApiChatListGetData,
  GetDataApiChatListGetResponses,
  GetCardListApiCardListGetData,
  GetCardListApiCardListGetResponses,
  GetOverviewContentApiWorkplaceOverviewContentGetData,
  GetOverviewContentApiWorkplaceOverviewContentGetResponses,
  GetPopularContentsApiWorkplacePopularContentsGetData,
  GetPopularContentsApiWorkplacePopularContentsGetResponses,
  GetContentPercentageApiWorkplaceContentPercentageGetData,
  GetContentPercentageApiWorkplaceContentPercentageGetResponses,
  GetAnnouncementApiWorkplaceAnnouncementGetData,
  GetAnnouncementApiWorkplaceAnnouncementGetResponses,
  GetDataAnalysisOverviewApiDataAnalysisOverviewGetData,
  GetDataAnalysisOverviewApiDataAnalysisOverviewGetResponses,
  GetContentPublishingApiDataAnalysisContentPublishingGetData,
  GetContentPublishingApiDataAnalysisContentPublishingGetResponses,
  GetAuthorListApiDataAnalysisAuthorListGetData,
  GetAuthorListApiDataAnalysisAuthorListGetResponses,
  GetMultiDimensionOverviewApiMultiDimensionOverviewGetData,
  GetMultiDimensionOverviewApiMultiDimensionOverviewGetResponses,
  GetMultiDimensionActivityApiMultiDimensionActivityGetData,
  GetMultiDimensionActivityApiMultiDimensionActivityGetResponses,
  GetMultiDimensionPolarApiMultiDimensionPolarGetData,
  GetMultiDimensionPolarApiMultiDimensionPolarGetResponses,
  GetMultiDimensionCardApiMultiDimensionCardGetData,
  GetMultiDimensionCardApiMultiDimensionCardGetResponses,
  GetMultiDimensionContentSourceApiMultiDimensionContentSourceGetData,
  GetMultiDimensionContentSourceApiMultiDimensionContentSourceGetResponses,
  GroupFormApiGroupFormPostData,
  GroupFormApiGroupFormPostResponses,
  GetBasicProfileApiBasicProfileGetData,
  GetBasicProfileApiBasicProfileGetResponses,
  GetAdjustmentApiAdjustmentGetData,
  GetAdjustmentApiAdjustmentGetResponses,
  GetUserProjectListApiUserProjectListGetData,
  GetUserProjectListApiUserProjectListGetResponses,
  GetUsersTeamListApiUsersTeamListGetData,
  GetUsersTeamListApiUsersTeamListGetResponses,
  GetUserLatestNewsApiUserLatestNewsGetData,
  GetUserLatestNewsApiUserLatestNewsGetResponses,
  GetUserNoticeApiUserNoticeGetData,
  GetUserNoticeApiUserNoticeGetResponses,
  SaveUserInfoApiUserSaveInfoPostData,
  SaveUserInfoApiUserSaveInfoPostResponses,
  GetUserVerifiedEnterpriseApiUserVerifiedEnterpriseGetData,
  GetUserVerifiedEnterpriseApiUserVerifiedEnterpriseGetResponses,
  GetUserVerifiedAuthListApiUserVerifiedAuthListGetData,
  GetUserVerifiedAuthListApiUserVerifiedAuthListGetResponses,
  GetListDataApiListGetData,
  GetListDataApiListGetResponses,
  MetricsMetricsGetData,
  MetricsMetricsGetResponses,
} from './types.gen';
import { client as _heyApiClient } from './client.gen';
import {
  listProjectResponseTransformer,
  createProjectResponseTransformer,
  deleteProjectResponseTransformer,
  updateProjectResponseTransformer,
  readDatasApiTestPlansGetResponseTransformer,
  createDataApiTestPlansPostResponseTransformer,
  deleteDataApiTestPlansIdDeleteResponseTransformer,
  readDataApiTestPlansIdGetResponseTransformer,
  updateDataApiTestPlansIdPutResponseTransformer,
  listTestCaseResponseTransformer,
  createTestCaseResponseTransformer,
  deleteTestCaseResponseTransformer,
  getTestCaseResponseTransformer,
  updateTestCaseResponseTransformer,
  listTestCaseNodeResponseTransformer,
  createTestCaseNodeResponseTransformer,
  deleteTestCaseNodeResponseTransformer,
  getTestCaseNodeResponseTransformer,
  updateTestCaseNodeResponseTransformer,
  listTestTaskResponseTransformer,
  createTestTaskResponseTransformer,
  deleteTestTaskResponseTransformer,
  getTestTaskResponseTransformer,
  updateTestTaskResponseTransformer,
  getTestTaskTreeResponseTransformer,
  listTestTaskRecordResponseTransformer,
  listTaskConfigsResponseTransformer,
  createTaskConfigResponseTransformer,
  deleteTaskConfigResponseTransformer,
  getTaskConfigResponseTransformer,
  updateTaskConfigResponseTransformer,
  caseResultApiTestTaskCaseResultPostResponseTransformer,
  listServerResponseTransformer,
  createServerResponseTransformer,
  deleteServerResponseTransformer,
  getServerResponseTransformer,
  updateServerResponseTransformer,
} from './transformers.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Auth:Jwt.Login
 */
export const authJwtLoginApiAuthJwtLoginPost = <
  ThrowOnError extends boolean = false
>(
  options: Options<AuthJwtLoginApiAuthJwtLoginPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AuthJwtLoginApiAuthJwtLoginPostResponses,
    AuthJwtLoginApiAuthJwtLoginPostErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    url: '/api/auth/jwt/login',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options.headers,
    },
  });
};

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogoutApiAuthJwtLogoutPost = <
  ThrowOnError extends boolean = false
>(
  options?: Options<AuthJwtLogoutApiAuthJwtLogoutPostData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    AuthJwtLogoutApiAuthJwtLogoutPostResponses,
    AuthJwtLogoutApiAuthJwtLogoutPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/auth/jwt/logout',
    ...options,
  });
};

/**
 * Register:Register
 */
export const registerRegisterApiAuthRegisterPost = <
  ThrowOnError extends boolean = false
>(
  options: Options<RegisterRegisterApiAuthRegisterPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    RegisterRegisterApiAuthRegisterPostResponses,
    RegisterRegisterApiAuthRegisterPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Users:Current User
 */
export const usersCurrentUserApiUsersMeGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<UsersCurrentUserApiUsersMeGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    UsersCurrentUserApiUsersMeGetResponses,
    UsersCurrentUserApiUsersMeGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/users/me',
    ...options,
  });
};

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUserApiUsersMePatch = <
  ThrowOnError extends boolean = false
>(
  options: Options<UsersPatchCurrentUserApiUsersMePatchData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    UsersPatchCurrentUserApiUsersMePatchResponses,
    UsersPatchCurrentUserApiUsersMePatchErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/users/me',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Users Search
 */
export const searchUser = <ThrowOnError extends boolean = false>(
  options?: Options<SearchUserData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    SearchUserResponses,
    SearchUserErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/users/search',
    ...options,
  });
};

/**
 * Upload Avatar
 */
export const uploadAvatar = <ThrowOnError extends boolean = false>(
  options: Options<UploadAvatarData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    UploadAvatarResponses,
    UploadAvatarErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/users/me/avatar',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });
};

/**
 * Users:Delete User
 */
export const usersDeleteUserApiUsersIdDelete = <
  ThrowOnError extends boolean = false
>(
  options: Options<UsersDeleteUserApiUsersIdDeleteData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    UsersDeleteUserApiUsersIdDeleteResponses,
    UsersDeleteUserApiUsersIdDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/users/{id}',
    ...options,
  });
};

/**
 * Users:User
 */
export const usersUserApiUsersIdGet = <ThrowOnError extends boolean = false>(
  options: Options<UsersUserApiUsersIdGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    UsersUserApiUsersIdGetResponses,
    UsersUserApiUsersIdGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/users/{id}',
    ...options,
  });
};

/**
 * Users:Patch User
 */
export const usersPatchUserApiUsersIdPatch = <
  ThrowOnError extends boolean = false
>(
  options: Options<UsersPatchUserApiUsersIdPatchData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    UsersPatchUserApiUsersIdPatchResponses,
    UsersPatchUserApiUsersIdPatchErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/users/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Lark Callback
 */
export const larkCallback = <ThrowOnError extends boolean = false>(
  options: Options<LarkCallbackData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    LarkCallbackResponses,
    LarkCallbackErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/auth/lark_callback',
    ...options,
  });
};

/**
 * Read Datas
 */
export const listProject = <ThrowOnError extends boolean = false>(
  options?: Options<ListProjectData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListProjectResponses,
    ListProjectErrors,
    ThrowOnError
  >({
    responseTransformer: listProjectResponseTransformer,
    responseType: 'json',
    url: '/api/projects',
    ...options,
  });
};

/**
 * Create Data
 */
export const createProject = <ThrowOnError extends boolean = false>(
  options: Options<CreateProjectData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateProjectResponses,
    CreateProjectErrors,
    ThrowOnError
  >({
    responseTransformer: createProjectResponseTransformer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/projects',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Read Data Options
 */
export const listProjectOptions = <ThrowOnError extends boolean = false>(
  options?: Options<ListProjectOptionsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListProjectOptionsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/projects/options',
    ...options,
  });
};

/**
 * Delete Data
 */
export const deleteProject = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProjectData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteProjectResponses,
    DeleteProjectErrors,
    ThrowOnError
  >({
    responseTransformer: deleteProjectResponseTransformer,
    responseType: 'json',
    url: '/api/projects/{id}',
    ...options,
  });
};

/**
 * Read Data
 */
export const getProject = <ThrowOnError extends boolean = false>(
  options: Options<GetProjectData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetProjectResponses,
    GetProjectErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/projects/{id}',
    ...options,
  });
};

/**
 * Update Data
 */
export const updateProject = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProjectData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateProjectResponses,
    UpdateProjectErrors,
    ThrowOnError
  >({
    responseTransformer: updateProjectResponseTransformer,
    responseType: 'json',
    url: '/api/projects/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Read Datas
 * 获取测试计划列表
 */
export const readDatasApiTestPlansGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadDatasApiTestPlansGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadDatasApiTestPlansGetResponses,
    ReadDatasApiTestPlansGetErrors,
    ThrowOnError
  >({
    responseTransformer: readDatasApiTestPlansGetResponseTransformer,
    responseType: 'json',
    url: '/api/test-plans',
    ...options,
  });
};

/**
 * Create Data
 * 创建测试计划并关联测试用例
 */
export const createDataApiTestPlansPost = <
  ThrowOnError extends boolean = false
>(
  options: Options<CreateDataApiTestPlansPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateDataApiTestPlansPostResponses,
    CreateDataApiTestPlansPostErrors,
    ThrowOnError
  >({
    responseTransformer: createDataApiTestPlansPostResponseTransformer,
    responseType: 'json',
    url: '/api/test-plans',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete Data
 * 删除测试计划
 */
export const deleteDataApiTestPlansIdDelete = <
  ThrowOnError extends boolean = false
>(
  options: Options<DeleteDataApiTestPlansIdDeleteData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteDataApiTestPlansIdDeleteResponses,
    DeleteDataApiTestPlansIdDeleteErrors,
    ThrowOnError
  >({
    responseTransformer: deleteDataApiTestPlansIdDeleteResponseTransformer,
    responseType: 'json',
    url: '/api/test-plans/{id}',
    ...options,
  });
};

/**
 * Read Data
 * 根据ID获取测试计划及其关联数据
 */
export const readDataApiTestPlansIdGet = <ThrowOnError extends boolean = false>(
  options: Options<ReadDataApiTestPlansIdGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    ReadDataApiTestPlansIdGetResponses,
    ReadDataApiTestPlansIdGetErrors,
    ThrowOnError
  >({
    responseTransformer: readDataApiTestPlansIdGetResponseTransformer,
    responseType: 'json',
    url: '/api/test-plans/{id}',
    ...options,
  });
};

/**
 * Update Data
 * 更新测试计划并管理关联的测试用例
 */
export const updateDataApiTestPlansIdPut = <
  ThrowOnError extends boolean = false
>(
  options: Options<UpdateDataApiTestPlansIdPutData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    UpdateDataApiTestPlansIdPutResponses,
    UpdateDataApiTestPlansIdPutErrors,
    ThrowOnError
  >({
    responseTransformer: updateDataApiTestPlansIdPutResponseTransformer,
    responseType: 'json',
    url: '/api/test-plans/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List Data
 */
export const listTestCase = <ThrowOnError extends boolean = false>(
  options?: Options<ListTestCaseData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListTestCaseResponses,
    ListTestCaseErrors,
    ThrowOnError
  >({
    responseTransformer: listTestCaseResponseTransformer,
    responseType: 'json',
    url: '/api/cases',
    ...options,
  });
};

/**
 * Create
 */
export const createTestCase = <ThrowOnError extends boolean = false>(
  options: Options<CreateTestCaseData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateTestCaseResponses,
    CreateTestCaseErrors,
    ThrowOnError
  >({
    responseTransformer: createTestCaseResponseTransformer,
    responseType: 'json',
    url: '/api/cases',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete
 */
export const deleteTestCase = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTestCaseData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteTestCaseResponses,
    DeleteTestCaseErrors,
    ThrowOnError
  >({
    responseTransformer: deleteTestCaseResponseTransformer,
    responseType: 'json',
    url: '/api/cases/{id}',
    ...options,
  });
};

/**
 * Read
 */
export const getTestCase = <ThrowOnError extends boolean = false>(
  options: Options<GetTestCaseData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetTestCaseResponses,
    GetTestCaseErrors,
    ThrowOnError
  >({
    responseTransformer: getTestCaseResponseTransformer,
    responseType: 'json',
    url: '/api/cases/{id}',
    ...options,
  });
};

/**
 * Update
 */
export const updateTestCase = <ThrowOnError extends boolean = false>(
  options: Options<UpdateTestCaseData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateTestCaseResponses,
    UpdateTestCaseErrors,
    ThrowOnError
  >({
    responseTransformer: updateTestCaseResponseTransformer,
    responseType: 'json',
    url: '/api/cases/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Validate
 */
export const validateTestCaseFile = <ThrowOnError extends boolean = false>(
  options: Options<ValidateTestCaseFileData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    ValidateTestCaseFileResponses,
    ValidateTestCaseFileErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/cases/validate',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });
};

/**
 * Import Cases
 */
export const importTestCaseFile = <ThrowOnError extends boolean = false>(
  options: Options<ImportTestCaseFileData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    ImportTestCaseFileResponses,
    ImportTestCaseFileErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/cases/import',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });
};

/**
 * Read Datas
 */
export const listTestCaseNode = <ThrowOnError extends boolean = false>(
  options?: Options<ListTestCaseNodeData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListTestCaseNodeResponses,
    ListTestCaseNodeErrors,
    ThrowOnError
  >({
    responseTransformer: listTestCaseNodeResponseTransformer,
    responseType: 'json',
    url: '/api/case_node',
    ...options,
  });
};

/**
 * Create
 */
export const createTestCaseNode = <ThrowOnError extends boolean = false>(
  options: Options<CreateTestCaseNodeData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateTestCaseNodeResponses,
    CreateTestCaseNodeErrors,
    ThrowOnError
  >({
    responseTransformer: createTestCaseNodeResponseTransformer,
    responseType: 'json',
    url: '/api/case_node',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Read Tree
 */
export const listTestCaseNodeTree = <ThrowOnError extends boolean = false>(
  options?: Options<ListTestCaseNodeTreeData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListTestCaseNodeTreeResponses,
    ListTestCaseNodeTreeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/case_node/tree',
    ...options,
  });
};

/**
 * Read Tree Cases
 */
export const listTestCaseNodeTreeCases = <ThrowOnError extends boolean = false>(
  options?: Options<ListTestCaseNodeTreeCasesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListTestCaseNodeTreeCasesResponses,
    ListTestCaseNodeTreeCasesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/case_node/tree/cases',
    ...options,
  });
};

/**
 * Delete
 */
export const deleteTestCaseNode = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTestCaseNodeData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteTestCaseNodeResponses,
    DeleteTestCaseNodeErrors,
    ThrowOnError
  >({
    responseTransformer: deleteTestCaseNodeResponseTransformer,
    responseType: 'json',
    url: '/api/case_node/{id}',
    ...options,
  });
};

/**
 * Read
 */
export const getTestCaseNode = <ThrowOnError extends boolean = false>(
  options: Options<GetTestCaseNodeData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetTestCaseNodeResponses,
    GetTestCaseNodeErrors,
    ThrowOnError
  >({
    responseTransformer: getTestCaseNodeResponseTransformer,
    responseType: 'json',
    url: '/api/case_node/{id}',
    ...options,
  });
};

/**
 * Update
 */
export const updateTestCaseNode = <ThrowOnError extends boolean = false>(
  options: Options<UpdateTestCaseNodeData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateTestCaseNodeResponses,
    UpdateTestCaseNodeErrors,
    ThrowOnError
  >({
    responseTransformer: updateTestCaseNodeResponseTransformer,
    responseType: 'json',
    url: '/api/case_node/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List
 * Retrieve data.
 */
export const listTestTask = <ThrowOnError extends boolean = false>(
  options?: Options<ListTestTaskData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListTestTaskResponses,
    ListTestTaskErrors,
    ThrowOnError
  >({
    responseTransformer: listTestTaskResponseTransformer,
    responseType: 'json',
    url: '/api/test_task',
    ...options,
  });
};

/**
 * Create
 * Create new data
 */
export const createTestTask = <ThrowOnError extends boolean = false>(
  options: Options<CreateTestTaskData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateTestTaskResponses,
    CreateTestTaskErrors,
    ThrowOnError
  >({
    responseTransformer: createTestTaskResponseTransformer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/test_task',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete
 * Delete data by ID.
 */
export const deleteTestTask = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTestTaskData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteTestTaskResponses,
    DeleteTestTaskErrors,
    ThrowOnError
  >({
    responseTransformer: deleteTestTaskResponseTransformer,
    responseType: 'json',
    url: '/api/test_task/{id}',
    ...options,
  });
};

/**
 * Get
 * Get by ID.
 */
export const getTestTask = <ThrowOnError extends boolean = false>(
  options: Options<GetTestTaskData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetTestTaskResponses,
    GetTestTaskErrors,
    ThrowOnError
  >({
    responseTransformer: getTestTaskResponseTransformer,
    responseType: 'json',
    url: '/api/test_task/{id}',
    ...options,
  });
};

/**
 * Update
 * Update by ID.
 */
export const updateTestTask = <ThrowOnError extends boolean = false>(
  options: Options<UpdateTestTaskData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateTestTaskResponses,
    UpdateTestTaskErrors,
    ThrowOnError
  >({
    responseTransformer: updateTestTaskResponseTransformer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/test_task/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Run
 * Run task data by ID.
 */
export const runTestTask = <ThrowOnError extends boolean = false>(
  options: Options<RunTestTaskData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    RunTestTaskResponses,
    RunTestTaskErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/test_task/{id}/run',
    ...options,
  });
};

/**
 * Tree
 * Run record data by ID.
 */
export const getTestTaskTree = <ThrowOnError extends boolean = false>(
  options: Options<GetTestTaskTreeData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetTestTaskTreeResponses,
    GetTestTaskTreeErrors,
    ThrowOnError
  >({
    responseTransformer: getTestTaskTreeResponseTransformer,
    responseType: 'json',
    url: '/api/test_task/{id}/tree',
    ...options,
  });
};

/**
 * Logs Sse
 * Get task logs
 */
export const getTestTaskLogSse = <ThrowOnError extends boolean = false>(
  options: Options<GetTestTaskLogSseData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetTestTaskLogSseResponses,
    GetTestTaskLogSseErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/test_task/{id}/log/stream',
    ...options,
  });
};

/**
 * Records
 * Get by ID.
 */
export const listTestTaskRecord = <ThrowOnError extends boolean = false>(
  options: Options<ListTestTaskRecordData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    ListTestTaskRecordResponses,
    ListTestTaskRecordErrors,
    ThrowOnError
  >({
    responseTransformer: listTestTaskRecordResponseTransformer,
    responseType: 'json',
    url: '/api/test_task/{id}/records',
    ...options,
  });
};

/**
 * List Task Configs
 * 获取任务配置列表
 */
export const listTaskConfigs = <ThrowOnError extends boolean = false>(
  options?: Options<ListTaskConfigsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListTaskConfigsResponses,
    ListTaskConfigsErrors,
    ThrowOnError
  >({
    responseTransformer: listTaskConfigsResponseTransformer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/task_config',
    ...options,
  });
};

/**
 * Create Task Config
 * 创建新的任务配置
 */
export const createTaskConfig = <ThrowOnError extends boolean = false>(
  options: Options<CreateTaskConfigData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateTaskConfigResponses,
    CreateTaskConfigErrors,
    ThrowOnError
  >({
    responseTransformer: createTaskConfigResponseTransformer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/task_config',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Read Data Options
 */
export const listTaskConfigOptions = <ThrowOnError extends boolean = false>(
  options?: Options<ListTaskConfigOptionsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListTaskConfigOptionsResponses,
    ListTaskConfigOptionsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/task_config/options',
    ...options,
  });
};

/**
 * Delete Task Config
 * 删除任务配置
 */
export const deleteTaskConfig = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTaskConfigData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteTaskConfigResponses,
    DeleteTaskConfigErrors,
    ThrowOnError
  >({
    responseTransformer: deleteTaskConfigResponseTransformer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/task_config/{task_config_id}',
    ...options,
  });
};

/**
 * Get Task Config
 * 获取任务配置详情
 */
export const getTaskConfig = <ThrowOnError extends boolean = false>(
  options: Options<GetTaskConfigData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetTaskConfigResponses,
    GetTaskConfigErrors,
    ThrowOnError
  >({
    responseTransformer: getTaskConfigResponseTransformer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/task_config/{task_config_id}',
    ...options,
  });
};

/**
 * Update Task Config
 * 更新任务配置
 */
export const updateTaskConfig = <ThrowOnError extends boolean = false>(
  options: Options<UpdateTaskConfigData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateTaskConfigResponses,
    UpdateTaskConfigErrors,
    ThrowOnError
  >({
    responseTransformer: updateTaskConfigResponseTransformer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/task_config/{task_config_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Download Log
 * Get task  record logs
 */
export const getTestTaskLogFile = <ThrowOnError extends boolean = false>(
  options: Options<GetTestTaskLogFileData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetTestTaskLogFileResponses,
    GetTestTaskLogFileErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/test_task/record/{record_id}/log/download',
    ...options,
  });
};

/**
 * Container Stop Data
 * Run record data by ID.
 */
export const containerStopTestTask = <ThrowOnError extends boolean = false>(
  options: Options<ContainerStopTestTaskData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    ContainerStopTestTaskResponses,
    ContainerStopTestTaskErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/test_task/record/{job_id}/container_stop',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Case Result
 */
export const caseResultApiTestTaskCaseResultPost = <
  ThrowOnError extends boolean = false
>(
  options: Options<CaseResultApiTestTaskCaseResultPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CaseResultApiTestTaskCaseResultPostResponses,
    CaseResultApiTestTaskCaseResultPostErrors,
    ThrowOnError
  >({
    responseTransformer: caseResultApiTestTaskCaseResultPostResponseTransformer,
    responseType: 'json',
    url: '/api/test_task/case_result',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Read Datas
 * 获取服务器列表
 */
export const listServer = <ThrowOnError extends boolean = false>(
  options?: Options<ListServerData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListServerResponses,
    ListServerErrors,
    ThrowOnError
  >({
    responseTransformer: listServerResponseTransformer,
    responseType: 'json',
    url: '/api/resource/server',
    ...options,
  });
};

/**
 * Create Data
 * 创建测试环境
 */
export const createServer = <ThrowOnError extends boolean = false>(
  options: Options<CreateServerData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateServerResponses,
    CreateServerErrors,
    ThrowOnError
  >({
    responseTransformer: createServerResponseTransformer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/resource/server',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Read Data Options
 */
export const listServerOptions = <ThrowOnError extends boolean = false>(
  options?: Options<ListServerOptionsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListServerOptionsResponses,
    ListServerOptionsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/resource/server/options',
    ...options,
  });
};

/**
 * Delete Data
 * 删除服务器
 */
export const deleteServer = <ThrowOnError extends boolean = false>(
  options: Options<DeleteServerData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteServerResponses,
    DeleteServerErrors,
    ThrowOnError
  >({
    responseTransformer: deleteServerResponseTransformer,
    responseType: 'json',
    url: '/api/resource/server/{id}',
    ...options,
  });
};

/**
 * Read Data
 * 根据ID获取服务器
 */
export const getServer = <ThrowOnError extends boolean = false>(
  options: Options<GetServerData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetServerResponses,
    GetServerErrors,
    ThrowOnError
  >({
    responseTransformer: getServerResponseTransformer,
    responseType: 'json',
    url: '/api/resource/server/{id}',
    ...options,
  });
};

/**
 * Update Data
 * 更新服务器
 */
export const updateServer = <ThrowOnError extends boolean = false>(
  options: Options<UpdateServerData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateServerResponses,
    UpdateServerErrors,
    ThrowOnError
  >({
    responseTransformer: updateServerResponseTransformer,
    responseType: 'json',
    url: '/api/resource/server/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Read Message
 */
export const readMessageApiMessageReadPost = <
  ThrowOnError extends boolean = false
>(
  options: Options<ReadMessageApiMessageReadPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    ReadMessageApiMessageReadPostResponses,
    ReadMessageApiMessageReadPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/message/read',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List Data
 */
export const listDataApiMessageListGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListDataApiMessageListGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListDataApiMessageListGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/message/list',
    ...options,
  });
};

/**
 * Get Data
 */
export const getDataApiChatListGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetDataApiChatListGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetDataApiChatListGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/chatList',
    ...options,
  });
};

/**
 * Get Card List
 */
export const getCardListApiCardListGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetCardListApiCardListGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetCardListApiCardListGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/cardList',
    ...options,
  });
};

/**
 * Get Overview Content
 */
export const getOverviewContentApiWorkplaceOverviewContentGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<
    GetOverviewContentApiWorkplaceOverviewContentGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    GetOverviewContentApiWorkplaceOverviewContentGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/workplace/overview-content',
    ...options,
  });
};

/**
 * Get Popular Contents
 */
export const getPopularContentsApiWorkplacePopularContentsGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<
    GetPopularContentsApiWorkplacePopularContentsGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    GetPopularContentsApiWorkplacePopularContentsGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/workplace/popular-contents',
    ...options,
  });
};

/**
 * Get Content Percentage
 */
export const getContentPercentageApiWorkplaceContentPercentageGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<
    GetContentPercentageApiWorkplaceContentPercentageGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    GetContentPercentageApiWorkplaceContentPercentageGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/workplace/content-percentage',
    ...options,
  });
};

/**
 * Get Announcement
 */
export const getAnnouncementApiWorkplaceAnnouncementGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<
    GetAnnouncementApiWorkplaceAnnouncementGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    GetAnnouncementApiWorkplaceAnnouncementGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/workplace/announcement',
    ...options,
  });
};

/**
 * Get Data Analysis Overview
 */
export const getDataAnalysisOverviewApiDataAnalysisOverviewGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<
    GetDataAnalysisOverviewApiDataAnalysisOverviewGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    GetDataAnalysisOverviewApiDataAnalysisOverviewGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/data-analysis/overview',
    ...options,
  });
};

/**
 * Get Content Publishing
 */
export const getContentPublishingApiDataAnalysisContentPublishingGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<
    GetContentPublishingApiDataAnalysisContentPublishingGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    GetContentPublishingApiDataAnalysisContentPublishingGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/data-analysis/content-publishing',
    ...options,
  });
};

/**
 * Get Author List
 */
export const getAuthorListApiDataAnalysisAuthorListGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<GetAuthorListApiDataAnalysisAuthorListGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetAuthorListApiDataAnalysisAuthorListGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/data-analysis/author-list',
    ...options,
  });
};

/**
 * Get Multi Dimension Overview
 */
export const getMultiDimensionOverviewApiMultiDimensionOverviewGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<
    GetMultiDimensionOverviewApiMultiDimensionOverviewGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    GetMultiDimensionOverviewApiMultiDimensionOverviewGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/multi-dimension/overview',
    ...options,
  });
};

/**
 * Get Multi Dimension Activity
 */
export const getMultiDimensionActivityApiMultiDimensionActivityGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<
    GetMultiDimensionActivityApiMultiDimensionActivityGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    GetMultiDimensionActivityApiMultiDimensionActivityGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/multi-dimension/activity',
    ...options,
  });
};

/**
 * Get Multi Dimension Polar
 */
export const getMultiDimensionPolarApiMultiDimensionPolarGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<
    GetMultiDimensionPolarApiMultiDimensionPolarGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    GetMultiDimensionPolarApiMultiDimensionPolarGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/multi-dimension/polar',
    ...options,
  });
};

/**
 * Get Multi Dimension Card
 */
export const getMultiDimensionCardApiMultiDimensionCardGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<
    GetMultiDimensionCardApiMultiDimensionCardGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    GetMultiDimensionCardApiMultiDimensionCardGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/multi-dimension/card',
    ...options,
  });
};

/**
 * Get Multi Dimension Content Source
 */
export const getMultiDimensionContentSourceApiMultiDimensionContentSourceGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<
    GetMultiDimensionContentSourceApiMultiDimensionContentSourceGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    GetMultiDimensionContentSourceApiMultiDimensionContentSourceGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/multi-dimension/content-source',
    ...options,
  });
};

/**
 * Group Form
 */
export const groupFormApiGroupFormPost = <ThrowOnError extends boolean = false>(
  options?: Options<GroupFormApiGroupFormPostData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    GroupFormApiGroupFormPostResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/groupForm',
    ...options,
  });
};

/**
 * Get Basic Profile
 */
export const getBasicProfileApiBasicProfileGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<GetBasicProfileApiBasicProfileGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetBasicProfileApiBasicProfileGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/basicProfile',
    ...options,
  });
};

/**
 * Get Adjustment
 */
export const getAdjustmentApiAdjustmentGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<GetAdjustmentApiAdjustmentGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetAdjustmentApiAdjustmentGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/adjustment',
    ...options,
  });
};

/**
 * Get User Project List
 */
export const getUserProjectListApiUserProjectListGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<GetUserProjectListApiUserProjectListGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetUserProjectListApiUserProjectListGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/user/projectList',
    ...options,
  });
};

/**
 * Get Users Team List
 */
export const getUsersTeamListApiUsersTeamListGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<GetUsersTeamListApiUsersTeamListGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetUsersTeamListApiUsersTeamListGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/users/team/list',
    ...options,
  });
};

/**
 * Get User Latest News
 */
export const getUserLatestNewsApiUserLatestNewsGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<GetUserLatestNewsApiUserLatestNewsGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetUserLatestNewsApiUserLatestNewsGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/user/latestNews',
    ...options,
  });
};

/**
 * Get User Notice
 */
export const getUserNoticeApiUserNoticeGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<GetUserNoticeApiUserNoticeGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetUserNoticeApiUserNoticeGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/user/notice',
    ...options,
  });
};

/**
 * Save User Info
 */
export const saveUserInfoApiUserSaveInfoPost = <
  ThrowOnError extends boolean = false
>(
  options?: Options<SaveUserInfoApiUserSaveInfoPostData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    SaveUserInfoApiUserSaveInfoPostResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/user/saveInfo',
    ...options,
  });
};

/**
 * Get User Verified Enterprise
 */
export const getUserVerifiedEnterpriseApiUserVerifiedEnterpriseGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<
    GetUserVerifiedEnterpriseApiUserVerifiedEnterpriseGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    GetUserVerifiedEnterpriseApiUserVerifiedEnterpriseGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/user/verified/enterprise',
    ...options,
  });
};

/**
 * Get User Verified Auth List
 */
export const getUserVerifiedAuthListApiUserVerifiedAuthListGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<
    GetUserVerifiedAuthListApiUserVerifiedAuthListGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    GetUserVerifiedAuthListApiUserVerifiedAuthListGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/user/verified/authList',
    ...options,
  });
};

/**
 * Get List Data
 */
export const getListDataApiListGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetListDataApiListGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetListDataApiListGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/list',
    ...options,
  });
};

/**
 * Metrics
 * Endpoint that serves Prometheus metrics.
 */
export const metricsMetricsGet = <ThrowOnError extends boolean = false>(
  options?: Options<MetricsMetricsGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    MetricsMetricsGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/metrics',
    ...options,
  });
};
