// This file is auto-generated by @hey-api/openapi-ts

import type {
  ListProjectResponse,
  CreateProjectResponse,
  DeleteProjectResponse,
  UpdateProjectResponse,
  ReadDatasApiTestPlansGetResponse,
  CreateDataApiTestPlansPostResponse,
  DeleteDataApiTestPlansIdDeleteResponse,
  ReadDataApiTestPlansIdGetResponse,
  UpdateDataApiTestPlansIdPutResponse,
  ListTestCaseResponse,
  CreateTestCaseResponse,
  DeleteTestCaseResponse,
  GetTestCaseResponse,
  UpdateTestCaseResponse,
  ListTestCaseNodeResponse,
  CreateTestCaseNodeResponse,
  DeleteTestCaseNodeResponse,
  GetTestCaseNodeResponse,
  UpdateTestCaseNodeResponse,
  ListTestTaskResponse,
  CreateTestTaskResponse,
  DeleteTestTaskResponse,
  GetTestTaskResponse,
  UpdateTestTaskResponse,
  GetTestTaskTreeResponse,
  ListTestTaskRecordResponse,
  ListTaskConfigsResponse,
  CreateTaskConfigResponse,
  DeleteTaskConfigResponse,
  GetTaskConfigResponse,
  UpdateTaskConfigResponse,
  CaseResultApiTestTaskCaseResultPostResponse,
  ListServerResponse,
  CreateServerResponse,
  DeleteServerResponse,
  GetServerResponse,
  UpdateServerResponse,
} from './types.gen';

const projectSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

const projectListSchemaResponseTransformer = (data: any) => {
  data.list = data.list.map((item: any) => {
    return projectSchemaResponseTransformer(item);
  });
  return data;
};

export const listProjectResponseTransformer = async (
  data: any
): Promise<ListProjectResponse> => {
  data = projectListSchemaResponseTransformer(data);
  return data;
};

export const createProjectResponseTransformer = async (
  data: any
): Promise<CreateProjectResponse> => {
  data = projectSchemaResponseTransformer(data);
  return data;
};

export const deleteProjectResponseTransformer = async (
  data: any
): Promise<DeleteProjectResponse> => {
  data = projectSchemaResponseTransformer(data);
  return data;
};

export const updateProjectResponseTransformer = async (
  data: any
): Promise<UpdateProjectResponse> => {
  data = projectSchemaResponseTransformer(data);
  return data;
};

const testPlanSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

const testPlanListSchemaResponseTransformer = (data: any) => {
  data.list = data.list.map((item: any) => {
    return testPlanSchemaResponseTransformer(item);
  });
  return data;
};

export const readDatasApiTestPlansGetResponseTransformer = async (
  data: any
): Promise<ReadDatasApiTestPlansGetResponse> => {
  data = testPlanListSchemaResponseTransformer(data);
  return data;
};

const testCaseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

const testPlanWithRelationsSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  if (data.cases) {
    data.cases = data.cases.map((item: any) => {
      return testCaseSchemaResponseTransformer(item);
    });
  }
  return data;
};

export const createDataApiTestPlansPostResponseTransformer = async (
  data: any
): Promise<CreateDataApiTestPlansPostResponse> => {
  data = testPlanWithRelationsSchemaResponseTransformer(data);
  return data;
};

export const deleteDataApiTestPlansIdDeleteResponseTransformer = async (
  data: any
): Promise<DeleteDataApiTestPlansIdDeleteResponse> => {
  data = testPlanSchemaResponseTransformer(data);
  return data;
};

export const readDataApiTestPlansIdGetResponseTransformer = async (
  data: any
): Promise<ReadDataApiTestPlansIdGetResponse> => {
  data = testPlanWithRelationsSchemaResponseTransformer(data);
  return data;
};

export const updateDataApiTestPlansIdPutResponseTransformer = async (
  data: any
): Promise<UpdateDataApiTestPlansIdPutResponse> => {
  data = testPlanWithRelationsSchemaResponseTransformer(data);
  return data;
};

const testCaseListSchemaResponseTransformer = (data: any) => {
  data.list = data.list.map((item: any) => {
    return testCaseSchemaResponseTransformer(item);
  });
  return data;
};

export const listTestCaseResponseTransformer = async (
  data: any
): Promise<ListTestCaseResponse> => {
  data = testCaseListSchemaResponseTransformer(data);
  return data;
};

export const createTestCaseResponseTransformer = async (
  data: any
): Promise<CreateTestCaseResponse> => {
  data = testCaseSchemaResponseTransformer(data);
  return data;
};

export const deleteTestCaseResponseTransformer = async (
  data: any
): Promise<DeleteTestCaseResponse> => {
  data = testCaseSchemaResponseTransformer(data);
  return data;
};

export const getTestCaseResponseTransformer = async (
  data: any
): Promise<GetTestCaseResponse> => {
  data = testCaseSchemaResponseTransformer(data);
  return data;
};

export const updateTestCaseResponseTransformer = async (
  data: any
): Promise<UpdateTestCaseResponse> => {
  data = testCaseSchemaResponseTransformer(data);
  return data;
};

const testCaseNodeSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

const testCaseNodeListSchemaResponseTransformer = (data: any) => {
  data.list = data.list.map((item: any) => {
    return testCaseNodeSchemaResponseTransformer(item);
  });
  return data;
};

export const listTestCaseNodeResponseTransformer = async (
  data: any
): Promise<ListTestCaseNodeResponse> => {
  data = testCaseNodeListSchemaResponseTransformer(data);
  return data;
};

export const createTestCaseNodeResponseTransformer = async (
  data: any
): Promise<CreateTestCaseNodeResponse> => {
  data = testCaseNodeSchemaResponseTransformer(data);
  return data;
};

export const deleteTestCaseNodeResponseTransformer = async (
  data: any
): Promise<DeleteTestCaseNodeResponse> => {
  data = testCaseNodeSchemaResponseTransformer(data);
  return data;
};

export const getTestCaseNodeResponseTransformer = async (
  data: any
): Promise<GetTestCaseNodeResponse> => {
  data = testCaseNodeSchemaResponseTransformer(data);
  return data;
};

export const updateTestCaseNodeResponseTransformer = async (
  data: any
): Promise<UpdateTestCaseNodeResponse> => {
  data = testCaseNodeSchemaResponseTransformer(data);
  return data;
};

const taskConfigSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

const testTaskListItemSchemaResponseTransformer = (data: any) => {
  if (data.config) {
    data.config = taskConfigSchemaResponseTransformer(data.config);
  }
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

const testTaskListSchemaResponseTransformer = (data: any) => {
  data.list = data.list.map((item: any) => {
    return testTaskListItemSchemaResponseTransformer(item);
  });
  return data;
};

export const listTestTaskResponseTransformer = async (
  data: any
): Promise<ListTestTaskResponse> => {
  data = testTaskListSchemaResponseTransformer(data);
  return data;
};

const testTaskSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

export const createTestTaskResponseTransformer = async (
  data: any
): Promise<CreateTestTaskResponse> => {
  data = testTaskSchemaResponseTransformer(data);
  return data;
};

export const deleteTestTaskResponseTransformer = async (
  data: any
): Promise<DeleteTestTaskResponse> => {
  data = testTaskSchemaResponseTransformer(data);
  return data;
};

export const getTestTaskResponseTransformer = async (
  data: any
): Promise<GetTestTaskResponse> => {
  data = testTaskSchemaResponseTransformer(data);
  return data;
};

export const updateTestTaskResponseTransformer = async (
  data: any
): Promise<UpdateTestTaskResponse> => {
  data = testTaskSchemaResponseTransformer(data);
  return data;
};

const testCaseNodeTreeItemOfTaskSchemaResponseTransformer = (data: any) => {
  if (data.children) {
    data.children = data.children.map((item: any) => {
      return testCaseNodeTreeItemOfTaskSchemaResponseTransformer(item);
    });
  }
  return data;
};

export const getTestTaskTreeResponseTransformer = async (
  data: any
): Promise<GetTestTaskTreeResponse> => {
  data = data.map((item: any) => {
    return testCaseNodeTreeItemOfTaskSchemaResponseTransformer(item);
  });
  return data;
};

const caseRecordSchemaResponseTransformer = (data: any) => {
  if (data.start_time) {
    data.start_time = new Date(data.start_time);
  }
  if (data.end_time) {
    data.end_time = new Date(data.end_time);
  }
  return data;
};

const taskRecordSchemaResponseTransformer = (data: any) => {
  if (data.created_at) {
    data.created_at = new Date(data.created_at);
  }
  if (data.case_records) {
    data.case_records = data.case_records.map((item: any) => {
      return caseRecordSchemaResponseTransformer(item);
    });
  }
  return data;
};

const taskRecordListSchemaResponseTransformer = (data: any) => {
  data.list = data.list.map((item: any) => {
    return taskRecordSchemaResponseTransformer(item);
  });
  return data;
};

export const listTestTaskRecordResponseTransformer = async (
  data: any
): Promise<ListTestTaskRecordResponse> => {
  data = taskRecordListSchemaResponseTransformer(data);
  return data;
};

const taskConfigListItemSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

const taskConfigListSchemaResponseTransformer = (data: any) => {
  data.list = data.list.map((item: any) => {
    return taskConfigListItemSchemaResponseTransformer(item);
  });
  return data;
};

export const listTaskConfigsResponseTransformer = async (
  data: any
): Promise<ListTaskConfigsResponse> => {
  data = taskConfigListSchemaResponseTransformer(data);
  return data;
};

export const createTaskConfigResponseTransformer = async (
  data: any
): Promise<CreateTaskConfigResponse> => {
  data = taskConfigSchemaResponseTransformer(data);
  return data;
};

export const deleteTaskConfigResponseTransformer = async (
  data: any
): Promise<DeleteTaskConfigResponse> => {
  data = taskConfigSchemaResponseTransformer(data);
  return data;
};

export const getTaskConfigResponseTransformer = async (
  data: any
): Promise<GetTaskConfigResponse> => {
  data = taskConfigSchemaResponseTransformer(data);
  return data;
};

export const updateTaskConfigResponseTransformer = async (
  data: any
): Promise<UpdateTaskConfigResponse> => {
  data = taskConfigSchemaResponseTransformer(data);
  return data;
};

export const caseResultApiTestTaskCaseResultPostResponseTransformer = async (
  data: any
): Promise<CaseResultApiTestTaskCaseResultPostResponse> => {
  data = caseRecordSchemaResponseTransformer(data);
  return data;
};

const serverSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

const listResponseServerSchemaResponseTransformer = (data: any) => {
  if (data.list) {
    data.list = data.list.map((item: any) => {
      return serverSchemaResponseTransformer(item);
    });
  }
  return data;
};

export const listServerResponseTransformer = async (
  data: any
): Promise<ListServerResponse> => {
  data = listResponseServerSchemaResponseTransformer(data);
  return data;
};

export const createServerResponseTransformer = async (
  data: any
): Promise<CreateServerResponse> => {
  data = serverSchemaResponseTransformer(data);
  return data;
};

export const deleteServerResponseTransformer = async (
  data: any
): Promise<DeleteServerResponse> => {
  data = serverSchemaResponseTransformer(data);
  return data;
};

export const getServerResponseTransformer = async (
  data: any
): Promise<GetServerResponse> => {
  data = serverSchemaResponseTransformer(data);
  return data;
};

export const updateServerResponseTransformer = async (
  data: any
): Promise<UpdateServerResponse> => {
  data = serverSchemaResponseTransformer(data);
  return data;
};
