// This file is auto-generated by @hey-api/openapi-ts

/**
 * BatchTestCaseFileValidateError
 */
export type BatchTestCaseFileValidateError = {
  /**
   * Detail
   */
  detail: Array<TestCaseFileValidateError>;
};

/**
 * BearerResponse
 */
export type BearerResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
};

/**
 * Body_auth_jwt_login_api_auth_jwt_login_post
 */
export type BodyAuthJwtLoginApiAuthJwtLoginPost = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

/**
 * Body_importTestCaseFile
 */
export type BodyImportTestCaseFile = {
  /**
   * File
   */
  file: Blob | File;
};

/**
 * Body_uploadAvatar
 */
export type BodyUploadAvatar = {
  /**
   * File
   */
  file: Blob | File;
};

/**
 * Body_validateTestCaseFile
 */
export type BodyValidateTestCaseFile = {
  /**
   * File
   */
  file: Blob | File;
};

/**
 * CaseRecord
 */
export type CaseRecord = {
  /**
   * Task Record Id
   */
  task_record_id: number;
  /**
   * Case Index
   */
  case_index: string;
  /**
   * Start Time
   */
  start_time?: Date | null;
  /**
   * End Time
   */
  end_time?: Date | null;
  /**
   * Duration
   */
  duration?: number | null;
  result?: CaseRecordStatus | null;
  /**
   * Id
   */
  id: number;
};

/**
 * CaseRecordCreateItem
 */
export type CaseRecordCreateItem = {
  /**
   * Case Node
   */
  case_node: string;
  /**
   * Result
   */
  result: string;
  /**
   * Case Index
   */
  case_index: string;
  /**
   * Start Time
   */
  start_time: Date;
  /**
   * End Time
   */
  end_time: Date;
  /**
   * Duration
   */
  duration: number;
};

/**
 * CaseRecordStatus
 */
export type CaseRecordStatus =
  | 'passed'
  | 'failed'
  | 'skipped'
  | 'xfailed'
  | 'xpassed'
  | 'error';

/**
 * CaseRecordStatus
 */
export const CaseRecordStatus = {
  PASSED: 'passed',
  FAILED: 'failed',
  SKIPPED: 'skipped',
  XFAILED: 'xfailed',
  XPASSED: 'xpassed',
  ERROR: 'error',
} as const;

/**
 * CaseResultCreate
 */
export type CaseResultCreate = {
  /**
   * Record Id
   */
  record_id: string;
  result: CaseRecordCreateItem;
};

/**
 * ContainerStatus
 */
export type ContainerStatus =
  | 'Running'
  | 'Stopped'
  | 'Failed'
  | 'Succeeded'
  | 'Unknown';

/**
 * ContainerStatus
 */
export const ContainerStatus = {
  RUNNING: 'Running',
  STOPPED: 'Stopped',
  FAILED: 'Failed',
  SUCCEEDED: 'Succeeded',
  UNKNOWN: 'Unknown',
} as const;

/**
 * ContainerStopData
 */
export type ContainerStopData = {
  status?: ContainerStatus | null;
  /**
   * Container Id
   */
  container_id: string;
  /**
   * Timestamp
   */
  timestamp: string;
};

/**
 * EnvVar
 */
export type EnvVar = {
  /**
   * Name
   */
  name: string;
  /**
   * Value
   */
  value: string;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
  /**
   * Detail
   */
  detail:
    | string
    | {
        [key: string]: string;
      };
};

/**
 * GenericErrorResponse
 */
export type GenericErrorResponse = {
  /**
   * Detail
   */
  detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ListResponse[Server]
 */
export type ListResponseServer = {
  /**
   * List
   */
  list?: Array<Server>;
  /**
   * Total
   */
  total?: number;
};

/**
 * Project
 */
export type Project = {
  /**
   * Name
   */
  name: string;
  /**
   * Git Repo
   */
  git_repo: string;
  /**
   * Branch
   */
  branch: string;
  /**
   * Owners
   */
  owners: Array<UserSearch>;
  /**
   * Qas
   */
  qas: Array<UserSearch>;
  /**
   * Devs
   */
  devs: Array<UserSearch>;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Updated At
   */
  updated_at: Date;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Git Repo
   */
  git_repo: string;
  /**
   * Branch
   */
  branch: string;
  /**
   * Owners
   */
  owners: Array<UserSearch>;
  /**
   * Qas
   */
  qas: Array<UserSearch>;
  /**
   * Devs
   */
  devs: Array<UserSearch>;
};

/**
 * ProjectList
 */
export type ProjectList = {
  /**
   * List
   */
  list: Array<Project>;
  /**
   * Total
   */
  total: number;
};

/**
 * ProjectOptions
 */
export type ProjectOptions = {
  /**
   * Name
   */
  name: string;
  /**
   * Id
   */
  id: number;
};

/**
 * ProjectUpdate
 */
export type ProjectUpdate = {
  /**
   * Name
   */
  name: string;
  /**
   * Git Repo
   */
  git_repo: string;
  /**
   * Branch
   */
  branch: string;
  /**
   * Owners
   */
  owners: Array<UserSearch>;
  /**
   * Qas
   */
  qas: Array<UserSearch>;
  /**
   * Devs
   */
  devs: Array<UserSearch>;
};

/**
 * ReadMessageRequest
 */
export type ReadMessageRequest = {
  /**
   * Ids
   */
  ids?: Array<number>;
};

/**
 * Server
 * Schema for retrieving a test server
 */
export type Server = {
  /**
   * Name
   * 服务器名称
   */
  name: string;
  /**
   * Project Id
   * 所属项目ID
   */
  project_id: number;
  /**
   * 环境状态
   */
  status?: ServerStatus | null;
  /**
   * Ip
   * IP地址
   */
  ip: string;
  /**
   * Sn
   * 序列号
   */
  sn?: string | null;
  /**
   * Id
   * 资源ID
   */
  id: number;
  /**
   * Owner Id
   * 创建人ID
   */
  owner_id: number;
  /**
   * Created At
   * 创建时间
   */
  created_at: Date;
  /**
   * Updated At
   * 更新时间
   */
  updated_at: Date;
  /**
   * 责任人
   */
  owner?: UserSearch | null;
  /**
   * Bmc Ip
   * BMC IP地址
   */
  bmc_ip: string | null;
  /**
   * Bmc Username
   * BMC 用户名
   */
  bmc_username: string | null;
  /**
   * Bmc Password
   * BMC 密码
   */
  bmc_password: string | null;
  /**
   * Port
   * 服务端口
   */
  port: number | null;
  /**
   * Username
   * 用户名
   */
  username: string | null;
  /**
   * Password
   * 密码
   */
  password: string | null;
};

/**
 * ServerCreate
 * Schema for creating a new server
 */
export type ServerCreate = {
  /**
   * Name
   * 服务器名称
   */
  name: string;
  /**
   * Ip
   * IP地址
   */
  ip: string;
  /**
   * Sn
   * 序列号
   */
  sn: string;
  /**
   * Bmc Ip
   * BMC IP地址
   */
  bmc_ip: string;
  /**
   * Bmc Username
   * BMC 用户名
   */
  bmc_username: string;
  /**
   * Bmc Password
   * BMC 密码
   */
  bmc_password: string;
  /**
   * Port
   * 服务端口
   */
  port: number;
  /**
   * Username
   * 用户名
   */
  username: string;
  /**
   * Password
   * 密码
   */
  password: string;
  /**
   * 环境状态
   */
  status?: ServerStatus | null;
};

/**
 * ServerInTask
 */
export type ServerInTask = {
  /**
   * Name
   * 服务器名称
   */
  name: string;
  /**
   * Ip
   * IP地址
   */
  ip: string;
  /**
   * Sn
   * 序列号
   */
  sn?: string | null;
  /**
   * Id
   * 资源ID
   */
  id: number;
  /**
   * Bmc Ip
   * BMC IP地址
   */
  bmc_ip: string | null;
  /**
   * Bmc Username
   * BMC 用户名
   */
  bmc_username: string | null;
  /**
   * Port
   * 服务端口
   */
  port: number | null;
  /**
   * Username
   * 用户名
   */
  username: string | null;
};

/**
 * ServerOptions
 * Schema for retrieving a test server options
 */
export type ServerOptions = {
  /**
   * Id
   * 资源ID
   */
  id: number;
  /**
   * Name
   * 环境名称
   */
  name: string;
};

/**
 * ServerStatus
 */
export type ServerStatus =
  | 'IDLE'
  | 'IN_USE'
  | 'MAINTENANCE'
  | 'ERROR'
  | 'UNKNOWN';

/**
 * ServerStatus
 */
export const ServerStatus = {
  IDLE: 'IDLE',
  IN_USE: 'IN_USE',
  MAINTENANCE: 'MAINTENANCE',
  ERROR: 'ERROR',
  UNKNOWN: 'UNKNOWN',
} as const;

/**
 * ServerUpdate
 * Schema for updating a test server
 */
export type ServerUpdate = {
  /**
   * Name
   * 服务器名称
   */
  name: string;
  /**
   * Ip
   * IP地址
   */
  ip: string;
  /**
   * Sn
   * 序列号
   */
  sn: string;
  /**
   * Bmc Ip
   * BMC IP地址
   */
  bmc_ip: string;
  /**
   * Bmc Username
   * BMC 用户名
   */
  bmc_username: string;
  /**
   * Bmc Password
   * BMC 密码
   */
  bmc_password: string;
  /**
   * Port
   * 服务端口
   */
  port: number;
  /**
   * Username
   * 用户名
   */
  username: string;
  /**
   * Password
   * 密码
   */
  password: string;
  /**
   * 环境状态
   */
  status?: ServerStatus | null;
};

/**
 * TaskConfig
 */
export type TaskConfig = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Env Vars
   */
  env_vars?: Array<EnvVar> | null;
  /**
   * Id
   */
  id: number;
  /**
   * Project Id
   */
  project_id: number;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Updated At
   */
  updated_at: Date;
};

/**
 * TaskConfigCreate
 */
export type TaskConfigCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Env Vars
   */
  env_vars?: Array<EnvVar> | null;
};

/**
 * TaskConfigList
 */
export type TaskConfigList = {
  /**
   * List
   */
  list: Array<TaskConfigListItem>;
  /**
   * Total
   */
  total: number;
};

/**
 * TaskConfigListItem
 */
export type TaskConfigListItem = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Env Vars
   */
  env_vars?: Array<EnvVar> | null;
  /**
   * Id
   */
  id: number;
  /**
   * Project Id
   */
  project_id: number;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Updated At
   */
  updated_at: Date;
  owner: UserSearch;
};

/**
 * TaskConfigOptions
 */
export type TaskConfigOptions = {
  /**
   * Name
   */
  name: string;
  /**
   * Id
   */
  id: number;
};

/**
 * TaskConfigUpdate
 */
export type TaskConfigUpdate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Env Vars
   */
  env_vars?: Array<EnvVar> | null;
};

/**
 * TaskRecord
 */
export type TaskRecord = {
  /**
   * Project Id
   */
  project_id: number;
  /**
   * Testplan Id
   */
  testplan_id?: number | null;
  /**
   * Failed Continue
   */
  failed_continue?: number | null;
  status?: TaskRecordStatus | null;
  /**
   * Branch
   */
  branch?: string | null;
  /**
   * Image
   */
  image?: string | null;
  /**
   * Repo
   */
  repo?: string | null;
  /**
   * Id
   */
  id: number;
  /**
   * Task Id
   */
  task_id: number;
  /**
   * Passed
   */
  passed?: number | null;
  /**
   * Failed
   */
  failed?: number | null;
  /**
   * Total
   */
  total?: number | null;
  /**
   * Created At
   */
  created_at?: Date | null;
  /**
   * Case Records
   */
  case_records?: Array<CaseRecord> | null;
};

/**
 * TaskRecordList
 */
export type TaskRecordList = {
  /**
   * List
   */
  list: Array<TaskRecord>;
  /**
   * Total
   */
  total: number;
};

/**
 * TaskRecordStatus
 */
export type TaskRecordStatus =
  | 'Created'
  | 'Running'
  | 'Passed'
  | 'Failed'
  | 'Canceled'
  | 'Error'
  | '';

/**
 * TaskRecordStatus
 */
export const TaskRecordStatus = {
  CREATED: 'Created',
  RUNNING: 'Running',
  PASSED: 'Passed',
  FAILED: 'Failed',
  CANCELED: 'Canceled',
  ERROR: 'Error',
  '': '',
} as const;

/**
 * TaskRunOut
 */
export type TaskRunOut = {
  /**
   * Id
   */
  id: number;
  /**
   * Creater
   */
  creater?: string | null;
  /**
   * Task Id
   */
  task_id: number;
  /**
   * Container Id
   */
  container_id?: string | null;
  /**
   * Agent Id
   */
  agent_id?: number | null;
};

/**
 * TaskStatus
 */
export type TaskStatus =
  | 'Created'
  | 'Running'
  | 'Passed'
  | 'Failed'
  | 'Canceled'
  | 'Error';

/**
 * TaskStatus
 */
export const TaskStatus = {
  CREATED: 'Created',
  RUNNING: 'Running',
  PASSED: 'Passed',
  FAILED: 'Failed',
  CANCELED: 'Canceled',
  ERROR: 'Error',
} as const;

/**
 * TestCase
 */
export type TestCase = {
  /**
   * Index
   */
  index: string;
  /**
   * Name
   */
  name: string;
  /**
   * Objective
   */
  objective: string;
  /**
   * Priority
   */
  priority: string;
  /**
   * Automated
   */
  automated?: number;
  /**
   * Automation
   */
  automation?: number;
  /**
   * Comment
   */
  comment?: string | null;
  /**
   * Depends
   */
  depends?: Array<unknown> | null;
  /**
   * Node Id
   */
  node_id?: number | null;
  /**
   * Module
   */
  module?: string | null;
  /**
   * Test Type
   */
  test_type?: string | null;
  /**
   * Expected
   */
  expected?: string | null;
  /**
   * Setup
   */
  setup?: string | null;
  /**
   * Step
   */
  step?: string | null;
  /**
   * Topo
   */
  topo?: string | null;
  /**
   * Project Id
   */
  project_id: number;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Updated At
   */
  updated_at: Date;
};

/**
 * TestCaseCreate
 */
export type TestCaseCreate = {
  /**
   * Index
   */
  index: string;
  /**
   * Name
   */
  name: string;
  /**
   * Objective
   */
  objective: string;
  /**
   * Priority
   */
  priority: string;
  /**
   * Automated
   */
  automated?: number;
  /**
   * Automation
   */
  automation?: number;
  /**
   * Comment
   */
  comment?: string | null;
  /**
   * Depends
   */
  depends?: Array<unknown> | null;
  /**
   * Node Id
   */
  node_id?: number | null;
  /**
   * Module
   */
  module?: string | null;
  /**
   * Test Type
   */
  test_type?: string | null;
  /**
   * Expected
   */
  expected?: string | null;
  /**
   * Setup
   */
  setup?: string | null;
  /**
   * Step
   */
  step?: string | null;
  /**
   * Topo
   */
  topo?: string | null;
};

/**
 * TestCaseFileValidateError
 */
export type TestCaseFileValidateError = {
  /**
   * Sheet
   */
  sheet: string;
  /**
   * Type
   */
  type: string;
  /**
   * Errors
   */
  errors: Array<string>;
};

/**
 * TestCaseList
 */
export type TestCaseList = {
  /**
   * List
   */
  list: Array<TestCase>;
  /**
   * Total
   */
  total: number;
};

/**
 * TestCaseNode
 */
export type TestCaseNode = {
  /**
   * Name
   */
  name: string;
  /**
   * Comment
   */
  comment?: string | null;
  /**
   * Parent Id
   */
  parent_id?: number | null;
  /**
   * Creater
   */
  creater?: string | null;
  /**
   * Id
   */
  id: number;
  /**
   * Project Id
   */
  project_id: number;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Updated At
   */
  updated_at: Date;
};

/**
 * TestCaseNodeCreate
 */
export type TestCaseNodeCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Comment
   */
  comment?: string | null;
  /**
   * Parent Id
   */
  parent_id?: number | null;
  /**
   * Creater
   */
  creater?: string | null;
};

/**
 * TestCaseNodeList
 */
export type TestCaseNodeList = {
  /**
   * List
   */
  list: Array<TestCaseNode>;
  /**
   * Total
   */
  total: number;
};

/**
 * TestCaseNodeTreeItemOfTask
 */
export type TestCaseNodeTreeItemOfTask = {
  /**
   * Key
   */
  key: string;
  /**
   * Title
   */
  title: string;
  /**
   * Children
   */
  children?: Array<TestCaseNodeTreeItemOfTask> | null;
  /**
   * Case Count
   */
  case_count?: number | null;
  /**
   * Selected Case Count
   */
  selected_case_count?: number | null;
};

/**
 * TestCaseNodeUpdate
 */
export type TestCaseNodeUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Comment
   */
  comment?: string | null;
  /**
   * Parent Id
   */
  parent_id?: number | null;
};

/**
 * TestCaseUpdate
 */
export type TestCaseUpdate = {
  /**
   * Index
   */
  index?: string | null;
  /**
   * Name
   */
  name?: string | null;
  /**
   * Objective
   */
  objective?: string | null;
  /**
   * Priority
   */
  priority?: string | null;
  /**
   * Automated
   */
  automated?: number | null;
  /**
   * Automation
   */
  automation?: number | null;
  /**
   * Comment
   */
  comment?: string | null;
  /**
   * Depends
   */
  depends?: Array<unknown> | null;
  /**
   * Node Id
   */
  node_id?: number | null;
  /**
   * Module
   */
  module?: string | null;
  /**
   * Test Type
   */
  test_type?: string | null;
  /**
   * Expected
   */
  expected?: string | null;
  /**
   * Setup
   */
  setup?: string | null;
  /**
   * Step
   */
  step?: string | null;
  /**
   * Topo
   */
  topo?: string | null;
};

/**
 * TestPlan
 */
export type TestPlan = {
  /**
   * Name
   */
  name: string;
  /**
   * Project Id
   */
  project_id: number;
  /**
   * Stage
   */
  stage?: number | null;
  /**
   * Owner Id
   */
  owner_id: string;
  /**
   * Status
   */
  status?: number | null;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Updated At
   */
  updated_at: Date;
};

/**
 * TestPlanCreate
 */
export type TestPlanCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Project Id
   */
  project_id: number;
  /**
   * Stage
   */
  stage?: number | null;
  /**
   * Owner Id
   */
  owner_id: string;
  /**
   * Status
   */
  status?: number | null;
  /**
   * Case Indexs
   */
  case_indexs?: Array<string> | null;
};

/**
 * TestPlanList
 */
export type TestPlanList = {
  /**
   * List
   */
  list: Array<TestPlan>;
  /**
   * Total
   */
  total: number;
};

/**
 * TestPlanUpdate
 */
export type TestPlanUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Project Id
   */
  project_id?: number | null;
  /**
   * Stage
   */
  stage?: number | null;
  /**
   * Owner Id
   */
  owner_id?: string | null;
  /**
   * Status
   */
  status?: number | null;
  /**
   * Case Indexs
   */
  case_indexs?: Array<string> | null;
};

/**
 * TestPlanWithRelations
 */
export type TestPlanWithRelations = {
  /**
   * Name
   */
  name: string;
  /**
   * Project Id
   */
  project_id: number;
  /**
   * Stage
   */
  stage?: number | null;
  /**
   * Owner Id
   */
  owner_id: string;
  /**
   * Status
   */
  status?: number | null;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Updated At
   */
  updated_at: Date;
  owner?: UserRead | null;
  /**
   * Cases
   */
  cases?: Array<TestCase> | null;
};

/**
 * TestTask
 */
export type TestTask = {
  /**
   * Name
   */
  name: string;
  /**
   * Failed Continue
   */
  failed_continue?: number;
  /**
   * Lark Notice
   */
  lark_notice?: number;
  /**
   * Config Id
   */
  config_id?: number | null;
  /**
   * Server Id
   */
  server_id?: number | null;
  /**
   * Lark Subscribe
   */
  lark_subscribe?: Array<unknown> | null;
  /**
   * Cases Index
   */
  cases_index?: Array<string> | null;
  /**
   * Desc
   */
  desc?: string | null;
  /**
   * Comment
   */
  comment?: string | null;
  /**
   * Id
   */
  id: number;
  owner: UserSearch;
  status?: TaskStatus | null;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Updated At
   */
  updated_at: Date;
};

/**
 * TestTaskCreate
 */
export type TestTaskCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Failed Continue
   */
  failed_continue?: number;
  /**
   * Lark Notice
   */
  lark_notice?: number;
  /**
   * Config Id
   */
  config_id?: number | null;
  /**
   * Server Id
   */
  server_id?: number | null;
  /**
   * Lark Subscribe
   */
  lark_subscribe?: Array<unknown> | null;
  /**
   * Cases
   */
  cases?: Array<string> | null;
  /**
   * Desc
   */
  desc?: string | null;
  /**
   * Comment
   */
  comment?: string | null;
};

/**
 * TestTaskList
 */
export type TestTaskList = {
  /**
   * List
   */
  list: Array<TestTaskListItem>;
  /**
   * Total
   */
  total: number;
};

/**
 * TestTaskListItem
 */
export type TestTaskListItem = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  owner: UserSearch;
  config?: TaskConfig | null;
  status?: TaskStatus | null;
  server?: ServerInTask | null;
  /**
   * Failed Continue
   */
  failed_continue?: number;
  /**
   * Lark Notice
   */
  lark_notice?: number;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Updated At
   */
  updated_at: Date;
};

/**
 * TestTaskUpdate
 */
export type TestTaskUpdate = {
  /**
   * Name
   */
  name: string;
  /**
   * Failed Continue
   */
  failed_continue?: number;
  /**
   * Lark Notice
   */
  lark_notice?: number;
  /**
   * Config Id
   */
  config_id?: number | null;
  /**
   * Server Id
   */
  server_id?: number | null;
  /**
   * Lark Subscribe
   */
  lark_subscribe?: Array<unknown> | null;
  /**
   * Cases
   */
  cases?: Array<string> | null;
  /**
   * Desc
   */
  desc?: string | null;
  /**
   * Comment
   */
  comment?: string | null;
};

/**
 * UpdateUserAvatar
 */
export type UpdateUserAvatar = {
  /**
   * Avatar
   */
  avatar: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
  /**
   * Name
   */
  name: string;
  /**
   * En Name
   */
  en_name?: string | null;
  /**
   * Avatar
   */
  avatar?: string | null;
  /**
   * Union Id
   */
  union_id?: string | null;
};

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: number;
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Is Verified
   */
  is_verified?: boolean;
  /**
   * Name
   */
  name: string;
  /**
   * En Name
   */
  en_name?: string | null;
  /**
   * Extra
   */
  extra?: {
    [key: string]: unknown;
  } | null;
  /**
   * Union Id
   */
  union_id?: string | null;
  /**
   * Avatar
   */
  avatar?: string | null;
  /**
   * Permissions
   */
  permissions?: {
    [key: string]: Array<string>;
  } | null;
};

/**
 * UserSearch
 */
export type UserSearch = {
  /**
   * Id
   */
  id: number;
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name: string;
  /**
   * En Name
   */
  en_name?: string | null;
  /**
   * Union Id
   */
  union_id?: string | null;
  /**
   * Avatar
   */
  avatar?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Password
   */
  password?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
  /**
   * Name
   */
  name?: string | null;
  /**
   * En Name
   */
  en_name?: string | null;
};

/**
 * ValidateSuccessResponse
 */
export type ValidateSuccessResponse = {
  /**
   * Message
   */
  message: string;
  /**
   * Valid Sheets
   */
  valid_sheets: Array<string>;
  /**
   * Warnings
   */
  warnings?: Array<TestCaseFileValidateError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type AuthJwtLoginApiAuthJwtLoginPostData = {
  body: BodyAuthJwtLoginApiAuthJwtLoginPost;
  path?: never;
  query?: never;
  url: '/api/auth/jwt/login';
};

export type AuthJwtLoginApiAuthJwtLoginPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthJwtLoginApiAuthJwtLoginPostError =
  AuthJwtLoginApiAuthJwtLoginPostErrors[keyof AuthJwtLoginApiAuthJwtLoginPostErrors];

export type AuthJwtLoginApiAuthJwtLoginPostResponses = {
  /**
   * Successful Response
   */
  200: BearerResponse;
};

export type AuthJwtLoginApiAuthJwtLoginPostResponse =
  AuthJwtLoginApiAuthJwtLoginPostResponses[keyof AuthJwtLoginApiAuthJwtLoginPostResponses];

export type AuthJwtLogoutApiAuthJwtLogoutPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/jwt/logout';
};

export type AuthJwtLogoutApiAuthJwtLogoutPostErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type AuthJwtLogoutApiAuthJwtLogoutPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RegisterRegisterApiAuthRegisterPostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: '/api/auth/register';
};

export type RegisterRegisterApiAuthRegisterPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterRegisterApiAuthRegisterPostError =
  RegisterRegisterApiAuthRegisterPostErrors[keyof RegisterRegisterApiAuthRegisterPostErrors];

export type RegisterRegisterApiAuthRegisterPostResponses = {
  /**
   * Successful Response
   */
  201: UserRead;
};

export type RegisterRegisterApiAuthRegisterPostResponse =
  RegisterRegisterApiAuthRegisterPostResponses[keyof RegisterRegisterApiAuthRegisterPostResponses];

export type UsersCurrentUserApiUsersMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/users/me';
};

export type UsersCurrentUserApiUsersMeGetErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type UsersCurrentUserApiUsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersCurrentUserApiUsersMeGetResponse =
  UsersCurrentUserApiUsersMeGetResponses[keyof UsersCurrentUserApiUsersMeGetResponses];

export type UsersPatchCurrentUserApiUsersMePatchData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: '/api/users/me';
};

export type UsersPatchCurrentUserApiUsersMePatchErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchCurrentUserApiUsersMePatchError =
  UsersPatchCurrentUserApiUsersMePatchErrors[keyof UsersPatchCurrentUserApiUsersMePatchErrors];

export type UsersPatchCurrentUserApiUsersMePatchResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchCurrentUserApiUsersMePatchResponse =
  UsersPatchCurrentUserApiUsersMePatchResponses[keyof UsersPatchCurrentUserApiUsersMePatchResponses];

export type SearchUserData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Q
     */
    q?: string;
  };
  url: '/api/users/search';
};

export type SearchUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SearchUserError = SearchUserErrors[keyof SearchUserErrors];

export type SearchUserResponses = {
  /**
   * Response Searchuser
   * Successful Response
   */
  200: Array<UserSearch>;
};

export type SearchUserResponse = SearchUserResponses[keyof SearchUserResponses];

export type UploadAvatarData = {
  body: BodyUploadAvatar;
  path?: never;
  query?: never;
  url: '/api/users/me/avatar';
};

export type UploadAvatarErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadAvatarError = UploadAvatarErrors[keyof UploadAvatarErrors];

export type UploadAvatarResponses = {
  /**
   * Successful Response
   */
  200: UpdateUserAvatar;
};

export type UploadAvatarResponse =
  UploadAvatarResponses[keyof UploadAvatarResponses];

export type UsersDeleteUserApiUsersIdDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: '/api/users/{id}';
};

export type UsersDeleteUserApiUsersIdDeleteErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersDeleteUserApiUsersIdDeleteError =
  UsersDeleteUserApiUsersIdDeleteErrors[keyof UsersDeleteUserApiUsersIdDeleteErrors];

export type UsersDeleteUserApiUsersIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UsersDeleteUserApiUsersIdDeleteResponse =
  UsersDeleteUserApiUsersIdDeleteResponses[keyof UsersDeleteUserApiUsersIdDeleteResponses];

export type UsersUserApiUsersIdGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: '/api/users/{id}';
};

export type UsersUserApiUsersIdGetErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUserApiUsersIdGetError =
  UsersUserApiUsersIdGetErrors[keyof UsersUserApiUsersIdGetErrors];

export type UsersUserApiUsersIdGetResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUserApiUsersIdGetResponse =
  UsersUserApiUsersIdGetResponses[keyof UsersUserApiUsersIdGetResponses];

export type UsersPatchUserApiUsersIdPatchData = {
  body: UserUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: '/api/users/{id}';
};

export type UsersPatchUserApiUsersIdPatchErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchUserApiUsersIdPatchError =
  UsersPatchUserApiUsersIdPatchErrors[keyof UsersPatchUserApiUsersIdPatchErrors];

export type UsersPatchUserApiUsersIdPatchResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchUserApiUsersIdPatchResponse =
  UsersPatchUserApiUsersIdPatchResponses[keyof UsersPatchUserApiUsersIdPatchResponses];

export type LarkCallbackData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Code
     */
    code: string;
  };
  url: '/api/auth/lark_callback';
};

export type LarkCallbackErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LarkCallbackError = LarkCallbackErrors[keyof LarkCallbackErrors];

export type LarkCallbackResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListProjectData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Pagesize
     */
    pageSize?: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Git Repo
     */
    git_repo?: string | null;
    /**
     * Branch
     */
    branch?: string | null;
    /**
     * Owners
     */
    owners?: number | null;
  };
  url: '/api/projects';
};

export type ListProjectErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListProjectError = ListProjectErrors[keyof ListProjectErrors];

export type ListProjectResponses = {
  /**
   * Successful Response
   */
  200: ProjectList;
};

export type ListProjectResponse =
  ListProjectResponses[keyof ListProjectResponses];

export type CreateProjectData = {
  body: ProjectCreate;
  path?: never;
  query?: never;
  url: '/api/projects';
};

export type CreateProjectErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
  /**
   * Successful Response
   */
  200: Project;
};

export type CreateProjectResponse =
  CreateProjectResponses[keyof CreateProjectResponses];

export type ListProjectOptionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/projects/options';
};

export type ListProjectOptionsResponses = {
  /**
   * Response Listprojectoptions
   * Successful Response
   */
  200: Array<ProjectOptions>;
};

export type ListProjectOptionsResponse =
  ListProjectOptionsResponses[keyof ListProjectOptionsResponses];

export type DeleteProjectData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: '/api/projects/{id}';
};

export type DeleteProjectErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
  /**
   * Successful Response
   */
  200: Project;
};

export type DeleteProjectResponse =
  DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: '/api/projects/{id}';
};

export type GetProjectErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetProjectError = GetProjectErrors[keyof GetProjectErrors];

export type GetProjectResponses = {
  /**
   * Response Getproject
   * Successful Response
   */
  200: unknown;
};

export type UpdateProjectData = {
  body: ProjectUpdate;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: '/api/projects/{id}';
};

export type UpdateProjectErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateProjectError = UpdateProjectErrors[keyof UpdateProjectErrors];

export type UpdateProjectResponses = {
  /**
   * Successful Response
   */
  200: Project;
};

export type UpdateProjectResponse =
  UpdateProjectResponses[keyof UpdateProjectResponses];

export type ReadDatasApiTestPlansGetData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Pagesize
     */
    pageSize?: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Owner Id
     */
    owner_id?: string | null;
    /**
     * Status
     */
    status?: number | null;
  };
  url: '/api/test-plans';
};

export type ReadDatasApiTestPlansGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadDatasApiTestPlansGetError =
  ReadDatasApiTestPlansGetErrors[keyof ReadDatasApiTestPlansGetErrors];

export type ReadDatasApiTestPlansGetResponses = {
  /**
   * Successful Response
   */
  200: TestPlanList;
};

export type ReadDatasApiTestPlansGetResponse =
  ReadDatasApiTestPlansGetResponses[keyof ReadDatasApiTestPlansGetResponses];

export type CreateDataApiTestPlansPostData = {
  body: TestPlanCreate;
  path?: never;
  query?: never;
  url: '/api/test-plans';
};

export type CreateDataApiTestPlansPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateDataApiTestPlansPostError =
  CreateDataApiTestPlansPostErrors[keyof CreateDataApiTestPlansPostErrors];

export type CreateDataApiTestPlansPostResponses = {
  /**
   * Successful Response
   */
  200: TestPlanWithRelations;
};

export type CreateDataApiTestPlansPostResponse =
  CreateDataApiTestPlansPostResponses[keyof CreateDataApiTestPlansPostResponses];

export type DeleteDataApiTestPlansIdDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: '/api/test-plans/{id}';
};

export type DeleteDataApiTestPlansIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteDataApiTestPlansIdDeleteError =
  DeleteDataApiTestPlansIdDeleteErrors[keyof DeleteDataApiTestPlansIdDeleteErrors];

export type DeleteDataApiTestPlansIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: TestPlan;
};

export type DeleteDataApiTestPlansIdDeleteResponse =
  DeleteDataApiTestPlansIdDeleteResponses[keyof DeleteDataApiTestPlansIdDeleteResponses];

export type ReadDataApiTestPlansIdGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: '/api/test-plans/{id}';
};

export type ReadDataApiTestPlansIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadDataApiTestPlansIdGetError =
  ReadDataApiTestPlansIdGetErrors[keyof ReadDataApiTestPlansIdGetErrors];

export type ReadDataApiTestPlansIdGetResponses = {
  /**
   * Successful Response
   */
  200: TestPlanWithRelations;
};

export type ReadDataApiTestPlansIdGetResponse =
  ReadDataApiTestPlansIdGetResponses[keyof ReadDataApiTestPlansIdGetResponses];

export type UpdateDataApiTestPlansIdPutData = {
  body: TestPlanUpdate;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: '/api/test-plans/{id}';
};

export type UpdateDataApiTestPlansIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateDataApiTestPlansIdPutError =
  UpdateDataApiTestPlansIdPutErrors[keyof UpdateDataApiTestPlansIdPutErrors];

export type UpdateDataApiTestPlansIdPutResponses = {
  /**
   * Successful Response
   */
  200: TestPlanWithRelations;
};

export type UpdateDataApiTestPlansIdPutResponse =
  UpdateDataApiTestPlansIdPutResponses[keyof UpdateDataApiTestPlansIdPutResponses];

export type ListTestCaseData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Pagesize
     */
    pageSize?: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Index
     */
    index?: string | null;
    /**
     * Priority
     */
    priority?: string | null;
    /**
     * Automation
     */
    automation?: number | null;
    /**
     * Automated
     */
    automated?: number | null;
    /**
     * Module
     */
    module?: string | null;
    /**
     * Node Id
     */
    node_id?: number | null;
  };
  url: '/api/cases';
};

export type ListTestCaseErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTestCaseError = ListTestCaseErrors[keyof ListTestCaseErrors];

export type ListTestCaseResponses = {
  /**
   * Successful Response
   */
  200: TestCaseList;
};

export type ListTestCaseResponse =
  ListTestCaseResponses[keyof ListTestCaseResponses];

export type CreateTestCaseData = {
  body: TestCaseCreate;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path?: never;
  query?: never;
  url: '/api/cases';
};

export type CreateTestCaseErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTestCaseError =
  CreateTestCaseErrors[keyof CreateTestCaseErrors];

export type CreateTestCaseResponses = {
  /**
   * Successful Response
   */
  200: TestCase;
};

export type CreateTestCaseResponse =
  CreateTestCaseResponses[keyof CreateTestCaseResponses];

export type DeleteTestCaseData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: '/api/cases/{id}';
};

export type DeleteTestCaseErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTestCaseError =
  DeleteTestCaseErrors[keyof DeleteTestCaseErrors];

export type DeleteTestCaseResponses = {
  /**
   * Successful Response
   */
  200: TestCase;
};

export type DeleteTestCaseResponse =
  DeleteTestCaseResponses[keyof DeleteTestCaseResponses];

export type GetTestCaseData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path: {
    /**
     * Id
     */
    id: number | string;
  };
  query?: never;
  url: '/api/cases/{id}';
};

export type GetTestCaseErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTestCaseError = GetTestCaseErrors[keyof GetTestCaseErrors];

export type GetTestCaseResponses = {
  /**
   * Successful Response
   */
  200: TestCase;
};

export type GetTestCaseResponse =
  GetTestCaseResponses[keyof GetTestCaseResponses];

export type UpdateTestCaseData = {
  body: TestCaseUpdate;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: '/api/cases/{id}';
};

export type UpdateTestCaseErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTestCaseError =
  UpdateTestCaseErrors[keyof UpdateTestCaseErrors];

export type UpdateTestCaseResponses = {
  /**
   * Successful Response
   */
  200: TestCase;
};

export type UpdateTestCaseResponse =
  UpdateTestCaseResponses[keyof UpdateTestCaseResponses];

export type ValidateTestCaseFileData = {
  body: BodyValidateTestCaseFile;
  path?: never;
  query?: never;
  url: '/api/cases/validate';
};

export type ValidateTestCaseFileErrors = {
  /**
   * 无有效 sheet, 所有 sheet 均缺少字段或为空
   */
  400: BatchTestCaseFileValidateError;
  /**
   * Validation Error
   */
  422: HttpValidationError;
  /**
   * 系统错误, 例如无法读取 Excel
   */
  500: GenericErrorResponse;
};

export type ValidateTestCaseFileError =
  ValidateTestCaseFileErrors[keyof ValidateTestCaseFileErrors];

export type ValidateTestCaseFileResponses = {
  /**
   * Successful Response
   */
  200: ValidateSuccessResponse;
};

export type ValidateTestCaseFileResponse =
  ValidateTestCaseFileResponses[keyof ValidateTestCaseFileResponses];

export type ImportTestCaseFileData = {
  body: BodyImportTestCaseFile;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path?: never;
  query?: {
    /**
     * Increment
     */
    increment?: boolean;
  };
  url: '/api/cases/import';
};

export type ImportTestCaseFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ImportTestCaseFileError =
  ImportTestCaseFileErrors[keyof ImportTestCaseFileErrors];

export type ImportTestCaseFileResponses = {
  /**
   * Response Importtestcasefile
   * Successful Response
   */
  200: unknown;
};

export type ListTestCaseNodeData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path?: never;
  query?: {
    /**
     * Parent Id
     */
    parent_id?: number | null;
    /**
     * Name
     */
    name?: string | null;
  };
  url: '/api/case_node';
};

export type ListTestCaseNodeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTestCaseNodeError =
  ListTestCaseNodeErrors[keyof ListTestCaseNodeErrors];

export type ListTestCaseNodeResponses = {
  /**
   * Successful Response
   */
  200: TestCaseNodeList;
};

export type ListTestCaseNodeResponse =
  ListTestCaseNodeResponses[keyof ListTestCaseNodeResponses];

export type CreateTestCaseNodeData = {
  body: TestCaseNodeCreate;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path?: never;
  query?: never;
  url: '/api/case_node';
};

export type CreateTestCaseNodeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTestCaseNodeError =
  CreateTestCaseNodeErrors[keyof CreateTestCaseNodeErrors];

export type CreateTestCaseNodeResponses = {
  /**
   * Successful Response
   */
  200: TestCaseNode;
};

export type CreateTestCaseNodeResponse =
  CreateTestCaseNodeResponses[keyof CreateTestCaseNodeResponses];

export type ListTestCaseNodeTreeData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path?: never;
  query?: never;
  url: '/api/case_node/tree';
};

export type ListTestCaseNodeTreeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTestCaseNodeTreeError =
  ListTestCaseNodeTreeErrors[keyof ListTestCaseNodeTreeErrors];

export type ListTestCaseNodeTreeResponses = {
  /**
   * Response Listtestcasenodetree
   * Successful Response
   */
  200: Array<unknown>;
};

export type ListTestCaseNodeTreeResponse =
  ListTestCaseNodeTreeResponses[keyof ListTestCaseNodeTreeResponses];

export type ListTestCaseNodeTreeCasesData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path?: never;
  query?: never;
  url: '/api/case_node/tree/cases';
};

export type ListTestCaseNodeTreeCasesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTestCaseNodeTreeCasesError =
  ListTestCaseNodeTreeCasesErrors[keyof ListTestCaseNodeTreeCasesErrors];

export type ListTestCaseNodeTreeCasesResponses = {
  /**
   * Response Listtestcasenodetreecases
   * Successful Response
   */
  200: Array<unknown>;
};

export type ListTestCaseNodeTreeCasesResponse =
  ListTestCaseNodeTreeCasesResponses[keyof ListTestCaseNodeTreeCasesResponses];

export type DeleteTestCaseNodeData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: '/api/case_node/{id}';
};

export type DeleteTestCaseNodeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTestCaseNodeError =
  DeleteTestCaseNodeErrors[keyof DeleteTestCaseNodeErrors];

export type DeleteTestCaseNodeResponses = {
  /**
   * Successful Response
   */
  200: TestCaseNode;
};

export type DeleteTestCaseNodeResponse =
  DeleteTestCaseNodeResponses[keyof DeleteTestCaseNodeResponses];

export type GetTestCaseNodeData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: '/api/case_node/{id}';
};

export type GetTestCaseNodeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTestCaseNodeError =
  GetTestCaseNodeErrors[keyof GetTestCaseNodeErrors];

export type GetTestCaseNodeResponses = {
  /**
   * Successful Response
   */
  200: TestCaseNode;
};

export type GetTestCaseNodeResponse =
  GetTestCaseNodeResponses[keyof GetTestCaseNodeResponses];

export type UpdateTestCaseNodeData = {
  body: TestCaseNodeUpdate;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: '/api/case_node/{id}';
};

export type UpdateTestCaseNodeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTestCaseNodeError =
  UpdateTestCaseNodeErrors[keyof UpdateTestCaseNodeErrors];

export type UpdateTestCaseNodeResponses = {
  /**
   * Successful Response
   */
  200: TestCaseNode;
};

export type UpdateTestCaseNodeResponse =
  UpdateTestCaseNodeResponses[keyof UpdateTestCaseNodeResponses];

export type ListTestTaskData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Pagesize
     */
    pageSize?: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Owner
     */
    owner?: string | null;
    /**
     * Status
     */
    status?: number | null;
  };
  url: '/api/test_task';
};

export type ListTestTaskErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTestTaskError = ListTestTaskErrors[keyof ListTestTaskErrors];

export type ListTestTaskResponses = {
  /**
   * Successful Response
   */
  200: TestTaskList;
};

export type ListTestTaskResponse =
  ListTestTaskResponses[keyof ListTestTaskResponses];

export type CreateTestTaskData = {
  body: TestTaskCreate;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path?: never;
  query?: never;
  url: '/api/test_task';
};

export type CreateTestTaskErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTestTaskError =
  CreateTestTaskErrors[keyof CreateTestTaskErrors];

export type CreateTestTaskResponses = {
  /**
   * Successful Response
   */
  200: TestTask;
};

export type CreateTestTaskResponse =
  CreateTestTaskResponses[keyof CreateTestTaskResponses];

export type DeleteTestTaskData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path: {
    /**
     * Id
     * The ID of the task
     */
    id: number;
  };
  query?: never;
  url: '/api/test_task/{id}';
};

export type DeleteTestTaskErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTestTaskError =
  DeleteTestTaskErrors[keyof DeleteTestTaskErrors];

export type DeleteTestTaskResponses = {
  /**
   * Successful Response
   */
  200: TestTask;
};

export type DeleteTestTaskResponse =
  DeleteTestTaskResponses[keyof DeleteTestTaskResponses];

export type GetTestTaskData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path: {
    /**
     * Id
     * The ID of the task
     */
    id: number;
  };
  query?: never;
  url: '/api/test_task/{id}';
};

export type GetTestTaskErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTestTaskError = GetTestTaskErrors[keyof GetTestTaskErrors];

export type GetTestTaskResponses = {
  /**
   * Successful Response
   */
  200: TestTask;
};

export type GetTestTaskResponse =
  GetTestTaskResponses[keyof GetTestTaskResponses];

export type UpdateTestTaskData = {
  body: TestTaskUpdate;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: '/api/test_task/{id}';
};

export type UpdateTestTaskErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTestTaskError =
  UpdateTestTaskErrors[keyof UpdateTestTaskErrors];

export type UpdateTestTaskResponses = {
  /**
   * Successful Response
   */
  200: TestTask;
};

export type UpdateTestTaskResponse =
  UpdateTestTaskResponses[keyof UpdateTestTaskResponses];

export type RunTestTaskData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path: {
    /**
     * Id
     * The ID of the task
     */
    id: number;
  };
  query?: never;
  url: '/api/test_task/{id}/run';
};

export type RunTestTaskErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RunTestTaskError = RunTestTaskErrors[keyof RunTestTaskErrors];

export type RunTestTaskResponses = {
  /**
   * Successful Response
   */
  200: TaskRunOut;
};

export type RunTestTaskResponse =
  RunTestTaskResponses[keyof RunTestTaskResponses];

export type GetTestTaskTreeData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path: {
    /**
     * Id
     * The ID of the task
     */
    id: number;
  };
  query?: never;
  url: '/api/test_task/{id}/tree';
};

export type GetTestTaskTreeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTestTaskTreeError =
  GetTestTaskTreeErrors[keyof GetTestTaskTreeErrors];

export type GetTestTaskTreeResponses = {
  /**
   * Response Gettesttasktree
   * Successful Response
   */
  200: Array<TestCaseNodeTreeItemOfTask>;
};

export type GetTestTaskTreeResponse =
  GetTestTaskTreeResponses[keyof GetTestTaskTreeResponses];

export type GetTestTaskLogSseData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path: {
    /**
     * Id
     * The ID of the task
     */
    id: number;
  };
  query?: never;
  url: '/api/test_task/{id}/log/stream';
};

export type GetTestTaskLogSseErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTestTaskLogSseError =
  GetTestTaskLogSseErrors[keyof GetTestTaskLogSseErrors];

export type GetTestTaskLogSseResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListTestTaskRecordData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path: {
    /**
     * Id
     * The ID of the task
     */
    id: number;
  };
  query?: never;
  url: '/api/test_task/{id}/records';
};

export type ListTestTaskRecordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTestTaskRecordError =
  ListTestTaskRecordErrors[keyof ListTestTaskRecordErrors];

export type ListTestTaskRecordResponses = {
  /**
   * Successful Response
   */
  200: TaskRecordList;
};

export type ListTestTaskRecordResponse =
  ListTestTaskRecordResponses[keyof ListTestTaskRecordResponses];

export type ListTaskConfigsData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path?: never;
  query?: {
    /**
     * Skip
     */
    skip?: number;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Name
     */
    name?: string | null;
  };
  url: '/api/task_config';
};

export type ListTaskConfigsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTaskConfigsError =
  ListTaskConfigsErrors[keyof ListTaskConfigsErrors];

export type ListTaskConfigsResponses = {
  /**
   * Successful Response
   */
  200: TaskConfigList;
};

export type ListTaskConfigsResponse =
  ListTaskConfigsResponses[keyof ListTaskConfigsResponses];

export type CreateTaskConfigData = {
  body: TaskConfigCreate;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path?: never;
  query?: never;
  url: '/api/task_config';
};

export type CreateTaskConfigErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTaskConfigError =
  CreateTaskConfigErrors[keyof CreateTaskConfigErrors];

export type CreateTaskConfigResponses = {
  /**
   * Successful Response
   */
  200: TaskConfig;
};

export type CreateTaskConfigResponse =
  CreateTaskConfigResponses[keyof CreateTaskConfigResponses];

export type ListTaskConfigOptionsData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path?: never;
  query?: never;
  url: '/api/task_config/options';
};

export type ListTaskConfigOptionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTaskConfigOptionsError =
  ListTaskConfigOptionsErrors[keyof ListTaskConfigOptionsErrors];

export type ListTaskConfigOptionsResponses = {
  /**
   * Response Listtaskconfigoptions
   * Successful Response
   */
  200: Array<TaskConfigOptions>;
};

export type ListTaskConfigOptionsResponse =
  ListTaskConfigOptionsResponses[keyof ListTaskConfigOptionsResponses];

export type DeleteTaskConfigData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path: {
    /**
     * Task Config Id
     * 任务配置ID
     */
    task_config_id: number;
  };
  query?: never;
  url: '/api/task_config/{task_config_id}';
};

export type DeleteTaskConfigErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTaskConfigError =
  DeleteTaskConfigErrors[keyof DeleteTaskConfigErrors];

export type DeleteTaskConfigResponses = {
  /**
   * Successful Response
   */
  200: TaskConfig;
};

export type DeleteTaskConfigResponse =
  DeleteTaskConfigResponses[keyof DeleteTaskConfigResponses];

export type GetTaskConfigData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path: {
    /**
     * Task Config Id
     * 任务配置ID
     */
    task_config_id: number;
  };
  query?: never;
  url: '/api/task_config/{task_config_id}';
};

export type GetTaskConfigErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTaskConfigError = GetTaskConfigErrors[keyof GetTaskConfigErrors];

export type GetTaskConfigResponses = {
  /**
   * Successful Response
   */
  200: TaskConfig;
};

export type GetTaskConfigResponse =
  GetTaskConfigResponses[keyof GetTaskConfigResponses];

export type UpdateTaskConfigData = {
  body: TaskConfigUpdate;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path: {
    /**
     * Task Config Id
     * 任务配置ID
     */
    task_config_id: number;
  };
  query?: never;
  url: '/api/task_config/{task_config_id}';
};

export type UpdateTaskConfigErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTaskConfigError =
  UpdateTaskConfigErrors[keyof UpdateTaskConfigErrors];

export type UpdateTaskConfigResponses = {
  /**
   * Successful Response
   */
  200: TaskConfig;
};

export type UpdateTaskConfigResponse =
  UpdateTaskConfigResponses[keyof UpdateTaskConfigResponses];

export type GetTestTaskLogFileData = {
  body?: never;
  path: {
    /**
     * Record Id
     * The ID of the task record to get
     */
    record_id: number;
  };
  query?: never;
  url: '/api/test_task/record/{record_id}/log/download';
};

export type GetTestTaskLogFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTestTaskLogFileError =
  GetTestTaskLogFileErrors[keyof GetTestTaskLogFileErrors];

export type GetTestTaskLogFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ContainerStopTestTaskData = {
  body: ContainerStopData;
  path: {
    /**
     * Job Id
     */
    job_id: number;
  };
  query?: never;
  url: '/api/test_task/record/{job_id}/container_stop';
};

export type ContainerStopTestTaskErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ContainerStopTestTaskError =
  ContainerStopTestTaskErrors[keyof ContainerStopTestTaskErrors];

export type ContainerStopTestTaskResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type CaseResultApiTestTaskCaseResultPostData = {
  body: CaseResultCreate;
  path?: never;
  query?: never;
  url: '/api/test_task/case_result';
};

export type CaseResultApiTestTaskCaseResultPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CaseResultApiTestTaskCaseResultPostError =
  CaseResultApiTestTaskCaseResultPostErrors[keyof CaseResultApiTestTaskCaseResultPostErrors];

export type CaseResultApiTestTaskCaseResultPostResponses = {
  /**
   * Successful Response
   */
  200: CaseRecord;
};

export type CaseResultApiTestTaskCaseResultPostResponse =
  CaseResultApiTestTaskCaseResultPostResponses[keyof CaseResultApiTestTaskCaseResultPostResponses];

export type ListServerData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Pagesize
     */
    pageSize?: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Owner
     */
    owner?: string | null;
    /**
     * Sn
     */
    sn?: string | null;
    /**
     * Ip
     */
    ip?: string | null;
  };
  url: '/api/resource/server';
};

export type ListServerErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListServerError = ListServerErrors[keyof ListServerErrors];

export type ListServerResponses = {
  /**
   * Successful Response
   */
  200: ListResponseServer;
};

export type ListServerResponse = ListServerResponses[keyof ListServerResponses];

export type CreateServerData = {
  body: ServerCreate;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path?: never;
  query?: never;
  url: '/api/resource/server';
};

export type CreateServerErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateServerError = CreateServerErrors[keyof CreateServerErrors];

export type CreateServerResponses = {
  /**
   * Successful Response
   */
  200: Server;
};

export type CreateServerResponse =
  CreateServerResponses[keyof CreateServerResponses];

export type ListServerOptionsData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path?: never;
  query?: never;
  url: '/api/resource/server/options';
};

export type ListServerOptionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListServerOptionsError =
  ListServerOptionsErrors[keyof ListServerOptionsErrors];

export type ListServerOptionsResponses = {
  /**
   * Response Listserveroptions
   * Successful Response
   */
  200: Array<ServerOptions>;
};

export type ListServerOptionsResponse =
  ListServerOptionsResponses[keyof ListServerOptionsResponses];

export type DeleteServerData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: '/api/resource/server/{id}';
};

export type DeleteServerErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteServerError = DeleteServerErrors[keyof DeleteServerErrors];

export type DeleteServerResponses = {
  /**
   * Successful Response
   */
  200: Server;
};

export type DeleteServerResponse =
  DeleteServerResponses[keyof DeleteServerResponses];

export type GetServerData = {
  body?: never;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: '/api/resource/server/{id}';
};

export type GetServerErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetServerError = GetServerErrors[keyof GetServerErrors];

export type GetServerResponses = {
  /**
   * Successful Response
   */
  200: Server;
};

export type GetServerResponse = GetServerResponses[keyof GetServerResponses];

export type UpdateServerData = {
  body: ServerUpdate;
  headers?: {
    /**
     * X-Project-Id
     * Project ID (optional)
     */
    'x-project-id'?: number | null;
  };
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: '/api/resource/server/{id}';
};

export type UpdateServerErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateServerError = UpdateServerErrors[keyof UpdateServerErrors];

export type UpdateServerResponses = {
  /**
   * Successful Response
   */
  200: Server;
};

export type UpdateServerResponse =
  UpdateServerResponses[keyof UpdateServerResponses];

export type ReadMessageApiMessageReadPostData = {
  body: ReadMessageRequest;
  path?: never;
  query?: never;
  url: '/api/message/read';
};

export type ReadMessageApiMessageReadPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadMessageApiMessageReadPostError =
  ReadMessageApiMessageReadPostErrors[keyof ReadMessageApiMessageReadPostErrors];

export type ReadMessageApiMessageReadPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListDataApiMessageListGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/message/list';
};

export type ListDataApiMessageListGetResponses = {
  /**
   * Response List Data Api Message List Get
   * Successful Response
   */
  200: unknown;
};

export type GetDataApiChatListGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/chatList';
};

export type GetDataApiChatListGetResponses = {
  /**
   * Response Get Data Api Chatlist Get
   * Successful Response
   */
  200: unknown;
};

export type GetCardListApiCardListGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/cardList';
};

export type GetCardListApiCardListGetResponses = {
  /**
   * Response Get Card List Api Cardlist Get
   * Successful Response
   */
  200: unknown;
};

export type GetOverviewContentApiWorkplaceOverviewContentGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/workplace/overview-content';
};

export type GetOverviewContentApiWorkplaceOverviewContentGetResponses = {
  /**
   * Response Get Overview Content Api Workplace Overview Content Get
   * Successful Response
   */
  200: unknown;
};

export type GetPopularContentsApiWorkplacePopularContentsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/workplace/popular-contents';
};

export type GetPopularContentsApiWorkplacePopularContentsGetResponses = {
  /**
   * Response Get Popular Contents Api Workplace Popular Contents Get
   * Successful Response
   */
  200: unknown;
};

export type GetContentPercentageApiWorkplaceContentPercentageGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/workplace/content-percentage';
};

export type GetContentPercentageApiWorkplaceContentPercentageGetResponses = {
  /**
   * Response Get Content Percentage Api Workplace Content Percentage Get
   * Successful Response
   */
  200: unknown;
};

export type GetAnnouncementApiWorkplaceAnnouncementGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/workplace/announcement';
};

export type GetAnnouncementApiWorkplaceAnnouncementGetResponses = {
  /**
   * Response Get Announcement Api Workplace Announcement Get
   * Successful Response
   */
  200: unknown;
};

export type GetDataAnalysisOverviewApiDataAnalysisOverviewGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/data-analysis/overview';
};

export type GetDataAnalysisOverviewApiDataAnalysisOverviewGetResponses = {
  /**
   * Response Get Data Analysis Overview Api Data Analysis Overview Get
   * Successful Response
   */
  200: unknown;
};

export type GetContentPublishingApiDataAnalysisContentPublishingGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/data-analysis/content-publishing';
};

export type GetContentPublishingApiDataAnalysisContentPublishingGetResponses = {
  /**
   * Response Get Content Publishing Api Data Analysis Content Publishing Get
   * Successful Response
   */
  200: unknown;
};

export type GetAuthorListApiDataAnalysisAuthorListGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/data-analysis/author-list';
};

export type GetAuthorListApiDataAnalysisAuthorListGetResponses = {
  /**
   * Response Get Author List Api Data Analysis Author List Get
   * Successful Response
   */
  200: unknown;
};

export type GetMultiDimensionOverviewApiMultiDimensionOverviewGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/multi-dimension/overview';
};

export type GetMultiDimensionOverviewApiMultiDimensionOverviewGetResponses = {
  /**
   * Response Get Multi Dimension Overview Api Multi Dimension Overview Get
   * Successful Response
   */
  200: unknown;
};

export type GetMultiDimensionActivityApiMultiDimensionActivityGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/multi-dimension/activity';
};

export type GetMultiDimensionActivityApiMultiDimensionActivityGetResponses = {
  /**
   * Response Get Multi Dimension Activity Api Multi Dimension Activity Get
   * Successful Response
   */
  200: unknown;
};

export type GetMultiDimensionPolarApiMultiDimensionPolarGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/multi-dimension/polar';
};

export type GetMultiDimensionPolarApiMultiDimensionPolarGetResponses = {
  /**
   * Response Get Multi Dimension Polar Api Multi Dimension Polar Get
   * Successful Response
   */
  200: unknown;
};

export type GetMultiDimensionCardApiMultiDimensionCardGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/multi-dimension/card';
};

export type GetMultiDimensionCardApiMultiDimensionCardGetResponses = {
  /**
   * Response Get Multi Dimension Card Api Multi Dimension Card Get
   * Successful Response
   */
  200: unknown;
};

export type GetMultiDimensionContentSourceApiMultiDimensionContentSourceGetData =
  {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/multi-dimension/content-source';
  };

export type GetMultiDimensionContentSourceApiMultiDimensionContentSourceGetResponses =
  {
    /**
     * Response Get Multi Dimension Content Source Api Multi Dimension Content Source Get
     * Successful Response
     */
    200: unknown;
  };

export type GroupFormApiGroupFormPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/groupForm';
};

export type GroupFormApiGroupFormPostResponses = {
  /**
   * Response Group Form Api Groupform Post
   * Successful Response
   */
  200: unknown;
};

export type GetBasicProfileApiBasicProfileGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/basicProfile';
};

export type GetBasicProfileApiBasicProfileGetResponses = {
  /**
   * Response Get Basic Profile Api Basicprofile Get
   * Successful Response
   */
  200: unknown;
};

export type GetAdjustmentApiAdjustmentGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/adjustment';
};

export type GetAdjustmentApiAdjustmentGetResponses = {
  /**
   * Response Get Adjustment Api Adjustment Get
   * Successful Response
   */
  200: unknown;
};

export type GetUserProjectListApiUserProjectListGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/projectList';
};

export type GetUserProjectListApiUserProjectListGetResponses = {
  /**
   * Response Get User Project List Api User Projectlist Get
   * Successful Response
   */
  200: unknown;
};

export type GetUsersTeamListApiUsersTeamListGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/users/team/list';
};

export type GetUsersTeamListApiUsersTeamListGetResponses = {
  /**
   * Response Get Users Team List Api Users Team List Get
   * Successful Response
   */
  200: unknown;
};

export type GetUserLatestNewsApiUserLatestNewsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/latestNews';
};

export type GetUserLatestNewsApiUserLatestNewsGetResponses = {
  /**
   * Response Get User Latest News Api User Latestnews Get
   * Successful Response
   */
  200: unknown;
};

export type GetUserNoticeApiUserNoticeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/notice';
};

export type GetUserNoticeApiUserNoticeGetResponses = {
  /**
   * Response Get User Notice Api User Notice Get
   * Successful Response
   */
  200: unknown;
};

export type SaveUserInfoApiUserSaveInfoPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/saveInfo';
};

export type SaveUserInfoApiUserSaveInfoPostResponses = {
  /**
   * Response Save User Info Api User Saveinfo Post
   * Successful Response
   */
  200: unknown;
};

export type GetUserVerifiedEnterpriseApiUserVerifiedEnterpriseGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/verified/enterprise';
};

export type GetUserVerifiedEnterpriseApiUserVerifiedEnterpriseGetResponses = {
  /**
   * Response Get User Verified Enterprise Api User Verified Enterprise Get
   * Successful Response
   */
  200: unknown;
};

export type GetUserVerifiedAuthListApiUserVerifiedAuthListGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/verified/authList';
};

export type GetUserVerifiedAuthListApiUserVerifiedAuthListGetResponses = {
  /**
   * Response Get User Verified Auth List Api User Verified Authlist Get
   * Successful Response
   */
  200: unknown;
};

export type GetListDataApiListGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/list';
};

export type GetListDataApiListGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type MetricsMetricsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/metrics';
};

export type MetricsMetricsGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseURL: 'http://localhost:8000' | (string & {});
};
